### ISSUE TITLE
Automate the generation of release notes

### ISSUE THREAD

**Issue by creachadair** [kythe/kythe#111]
In previous releases, we have generally assembled the release notes by manually trawling the commit logs. While a certain amount of manual vetting is probably OK, most of the process of adding release notes should be automated. 

Good commit-log hygiene might help with this, and/or we may want to consider using an explicit tagging mechanism for what gets counted as "interesting" for release purposes.

**Comment by jrtom** [comment]
Guava has a RELNOTES section in their changelist descriptions that is used to construct release notes (which can be set to "n/a" for changes that aren't user-facing).  I don't know how easy it would be to add a pre-merge check to verify that such text was in a PR commit, but that's a model we might consider.
