### ISSUE TITLE
Replace delimited stream with more robust format

### ISSUE THREAD

**Issue by schroederc** [kythe/kythe#131]
[Riegeli](https://github.com/google/riegeli/) is the leading contender, but we would need to port it.

**Comment by schroederc** [comment]
I have a prototype Riegeli Reader/Writer in Go.  As a first step, this is all we should need once it has been cleaned up.  We can pass all indexer outputs through `entrystream` to convert to Riegeli before post-processing.

**Comment by zellyn** [comment]
Have you thought about splitting off your Riegeli Go implementation as a separate repo? It seems it would be generally useful.

**Comment by schroederc** [comment]
Unfortunately, the Riegeli implementation is still very much experimental and not very well supported.  Due to changing priorities, I've only had partial time to polish the code.  It can be used but it is sure to have bugs and will be a risk on the user.
