### ISSUE TITLE
Define schema components for modifiers

### ISSUE THREAD

**Issue by creachadair** [kythe/kythe#2978]
Certain nodes have additional Boolean attributes, which are semantically interesting independent of their identity. These often correspond to language keywords such as `static` or `public`, or may arise from metasyntactic annotations (e.g., `@Deprecated`) or conventions of documentation (e.g., the [deprecation comments in Go](https://rakyll.org/deprecated/)).

Update the schema to include a way for indexers to add such annotations uniformly, where it makes sense to do so. Access and visibility modifiers, deprecation, and linkage are good candidates, since these concepts are shared across languages.

**Comment by creachadair** [comment]
The last time we discussed this topic, the leading proposal seems to have been to define a `tag/` namespace of facts, e.g., 

    A.tag/deprecated "use this other thing instead"

For tags without meaningful values (i.e., they are present or absent only), `""` suffices as a value.

    A.tag/static ""

But we would probably want to define at least some categories of these, and we might want to consider whether it's sensible to further partition the namespace by, say `tag/visibility/…` or similar.

**Comment by jrtom** [comment]
Might be worth considering having two categories of tag-likes: ones that have values and ones that don't (since a lot of them don't).

**Comment by jrtom** [comment]
Note that there are (in Java, at least) three different kinds of things here:
* modifiers, e.g.: "public", "static", "final"
  (all built-in, none take 
* [annotations](https://docs.oracle.com/javase/tutorial/java/annotations/predefined.html), e.g.: "@Deprecated" [capital "D"], "@SuppressWarnings("unchecked")", "@VisibleForTesting"
  (some are built into the Java API, some aren't; some take parameters, some don't)
* [Javadoc tags](https://www.oracle.com/technetwork/java/javase/documentation/index-137868.html#tag), e.g.: "@deprecated because it's terrible" [lowercase "d"] and "@since 13.0"
  (defined by the Javadoc tool; not sure whether there are examples that don't take parameters or not)

I'm not sure which of these is in scope for this request, but we may want to consider calling them different things in the schema, if only because there's nothing (that I know of) that prevents these types of things having distinct names.

**Comment by creachadair** [comment]
Java-style annotations are already indexed separately, so I don't think we need to cover those explicitly here—we already record their declaration sites and their association to the entity they annotate.

The thing that's distinct here is the _property_ the annotation infuses into the object, e.g., of being deprecated. One could derive that by knowing that thus-and-such annotation means deprecation, and tracing the connection, but "deprecation" is one of those cross-language concepts that probably deserves its own description. 

The important part, I think, isn't so much the syntax of how the modifier is attached, but its effect on the meaning. (Of course "Modifier" is itself a somewhat ambiguous term—as with many of these labels, its meaning may differ subtly from one language to another, and we're looking ideally for a meaning that we can share. That may require choosing a different name).

**Comment by cushon** [comment]
It looks like `tag/deprecated` was added by 895104e85a676a718fafe79e1cb530dd4664eb12.

**Comment by jaysachs** [comment]
An unresolved issue here is how to represent the visibility modifiers in Java/C++/Kotlin/C#/TypeScript etc. I think creachadair suggested

tag/visibility/public ""
tag/visibility/protected ""

vs

tag/public ""
tag/protected ""

but the other option is

tag/visibility "public|protected|private"

which can work given that those states are mutually exclusive, syntactically at least. I don't think it makes sense to bake in language semantics (and thus when something is "public" also attribute "protected", "package", and "private"). 

Are there cases where a language permits multiple visibility "modifiers"?

Should this encompass Bazel where visibility is not a modifier but something more complex?

**Comment by shahms** [comment]
The suggestion in #1175 was towards mods/visibility = public|protected|package|etc.

**Comment by jaysachs** [comment]
Ok, trying to gather the state of the world here.

Implemented:
* tag/deprecated
* tag/static

Proposed:
* mod/visibility = public|protected|private|package|etc

Why is visibility under "mod/" and not under "tag/" alongside "static"? 

Presumably "const", "volatile" and "mutable" should be with "static"? 

What about things like C++ "explicit" and "inline"? We can ignore them, but if we do capture them, are they also "tag/..."?

**Comment by shahms** [comment]
`inline` barely has schema-relevant meaning in C++ and should probably be treated like we would treat `[[attributes]]` (same as `explicit`, I think). `const` and `volatile` are reflected in the type node directly (but `mutable` is not part of the type system).

**Comment by zrlk** [comment]
CVR-qualifiers are reflected in the type system. `explicit` and `inline` (and `const` on a function, and a bunch of other modifiers) should live under the `tag/` namespace.

I think `visibility` can live as a top-level fact with an unsurprising set of possible values (public, private, protected, package). I assert without proof that the majority of languages people are interested in just steal the Java/C++ visibility model. We can shove Go into the same model by treating exported things as public and non-exported as package (probably).

We'll have to deal with languages with actual modules differently, but I don't think those are in scope here. Nor is the representation of C++ friends.

**Comment by shahms** [comment]
For C++ modules I *think* we can treat exported namespace-scope entities as "public" as well and non-exported ones as "package" (with internal-linkage being "private"? I'll have to read up on how modules and static/anonymous namespaces interact).

**Comment by creachadair** [comment]
> Proposed:
> 
> * mod/visibility = public|protected|private|package|etc
> 
> Why is visibility under "mod/" and not under "tag/" alongside "static"?

I haven't thought about this in a while, but I think the idea was that "tags" are binary, e.g., either the entity has the tag or not, and the value is either meaningless or purely descriptive and could be changed without affecting the meaning. Modifiers, on the other hand, are more general categories.

I don't remember if we had other reasons, and I am not defending the separation per se—only that I think that's what we discussed.

**Comment by jaysachs** [comment]
I think zrlk's suggestion of a top-level "visibility" makes sense, and deftly avoids wondering about the prefix "mod".

**Comment by jaysachs** [comment]
What's to be done for redundant (or conversely, lack of redundant) visibility qualifiers? For instance:

```java
public interface A {
  public void foo();
}

public interface B {
  void bar();
}
```

Which of `foo` and `bar` should annotated with visibility `public`? (Similar question for C++ struct vs class default visibility rules.)

Note that currently we don't distinguish "interface" from "class" in Java node subkinds (though we do apparently separate "struct" from "class"  in C++), so there's no way to tell that `bar` is public due to its context unless we add such a fact.

**Comment by creachadair** [comment]
> What's to be done for redundant (or conversely, lack of redundant) visibility qualifiers? 

I'm not sure I fully understand your examples: As I understand, all the methods of an `interface` declaration (in Java) are implicitly public anyway, regardless. A private method can _satisfy_ the interface (since Java 9 at least), but that's on the implementation not the type declaration. I _think_ what you're trying to get at is a case where modifying an enclosing structure is shorthand for applying that modifier to enclosed elements.

In the syntactic model, it's physically connected to the outer structure, so that's where it goes; in a semantic model, arguably it should be propagated to all (and only) the objects it applies to.

I'd argue it comes down to what question(s) you and/or the user want to answer: If the user is looking for places in the code where the modifier was used, the syntactic viewpoint makes sense. If the important question is "where are there public methods, regardless whether they were labelled explicitly as such" then the semantic viewpoint makes sense. You could make a case for having both, but there may be a tradeoff of how much data you want to store in the graph.

**Comment by jaysachs** [comment]
You're right, I didn't spell out the question(s). I'd been implicitly thinking of queries like "find calls to non-public methods in some context", in which case the semantic approach makes sense. Any calls to an un-tagged Java interface method would be calls to a public method in this sense.

There are certainly other questions that could be interesting, and might "prefer" the syntactic approach.

**Comment by shahms** [comment]
This is, to some extent, asking how language neutral we want this to be vs redundant.  While it's true that you can tell what the default visibility of an entity is given the language and parent (`(java, interface) -> public`, `(java, class) -> package`, `(c++, class) -> private`) actually determining that is a pretty obnoxious query (potentially with a lot of expensive joins, depending on the query language).  I think consistency is an important factor, especially when dealing with partial support by language.  If the language indexer supports visibility facts, it should emit them even for the default.  If it does not, well, those facts won't exist.

Aside: we *do* differentiate Java `interface` from Java `class` by kind (not subkind).

**Comment by shahms** [comment]
For the syntactic case, we can include or omit the visibility annotation on the `MarkedSource`, potentially.

**Comment by hildrum** [comment]
FWIW, I would expect both foo and bar to be annotated as public if they are indeed public whether they have the public keyword in front of them or not.
