### ISSUE TITLE
Support analyzing kzip files with multiple compilation units

### ISSUE THREAD

**Issue by schroederc** [kythe/kythe#3120]
- [X] Support in [go_indexer.go](https://github.com/google/kythe/blob/6d1bfe86d8350d3e9bf402542fa43551bbd88bb1/kythe/go/indexer/cmd/go_indexer/go_indexer.go#L173)
- [x] Support in [JavaIndexer.java](https://github.com/google/kythe/blob/f32f399c943c6d6be65648918c54a45b4812b0ac/kythe/java/com/google/devtools/kythe/analyzers/java/JavaIndexer.java#L107)
- [x] Support in [ClassFileIndexer.java](https://github.com/google/kythe/blob/f32f399c943c6d6be65648918c54a45b4812b0ac/kythe/java/com/google/devtools/kythe/analyzers/jvm/ClassFileIndexer.java#L101)
- [x] Support in C++ [frontend.cc](https://github.com/google/kythe/blob/c69b7c50650f7b51f037193f33ed706fe1d4aeee/kythe/cxx/common/indexing/frontend.cc#L139)

**Comment by justbuchanan** [comment]
Currently when using index pack files, usage looks like `cxx_indexer --index_pack=path/to/file hash [more hashes...]`

Do we want also want the ability to select specific CU hashes when working with kzips, or should we always read all CUs when given a kzip file? From what I can tell, the java and go indexers just read all contents of kzips.

**Comment by schroederc** [comment]
I think analyzing all compilations in a `.kzip` is a good default.

**Comment by justbuchanan** [comment]
C++ support added in #3232.
