### ISSUE TITLE
Write a generic kzip generating tool

### ISSUE THREAD

**Issue by shahms** [kythe/kythe#3146]
Essentially, something which will construct a suitable .kzip file from a list of files and compiler flags.  This is mostly a matter of creating a CompilationUnit protocol message and then zipping it and the provided files into a .kzip file.

**Comment by shahms** [comment]
This is `kzip create` from `//kythe/go/platform/tools/kzip`; however it was originally written to replace `kindex_file_generator` so lacks some functionality:

1. Should support adding a new CU to an existing .kzip
2. Accept a --config argument for the standard JSON path remapping
3. Needs to be able to set:
  a. `arguments`
  b. `environment`
  c. `working_directory`
  d. `has_compile_errors`
  e. `entry_context` ?

It should probably support using the "official" environment variables as well, rather than just command line arguments, but we'd need to document what those are first.

**Comment by creachadair** [comment]
https://godoc.org/github.com/kelseyhightower/envconfig might be helpful for this purpose.
