### ISSUE TITLE
Include links to tools required by commit hooks

### ISSUE THREAD

**Issue by shahms** [kythe/kythe#3222]
All of the tools mentioned in "contributing" should include links on where to find them, particularly for those which aren't typically packaged for distributions and have uselessly generic names (spellcheck, ahem):

* arcanist
* buildifier
* clang-format
* commitlint (and @commitlint/config-conventional)
* gofmt
* google-java-format
* jq
* shellcheck

**Comment by shahms** [comment]
lol, fair enough. That helps a bit, but still leaves commitlint and the others needing at least a pointer on where to find them.

**Comment by shahms** [comment]
Please document how to install commitlint. Node/npm is terrible.

**Comment by schroederc** [comment]
#3259 makes installing `commitlint` a non-issue.
