### ISSUE TITLE
flaky test: //kythe/go/util/riegeli:riegeli_test

### ISSUE THREAD

**Issue by bzz** [kythe/kythe#3246]
Looks like 1 test fails on `bazel //...` on macOS

```
Executing tests from //kythe/go/util/riegeli:riegeli_test
-----------------------------------------------------------------------------
2018/11/12 20:55:10 Compressed size of "TestReadWriteProto/zstd": 218225 bytes
2018/11/12 20:55:10 Compressed size of "TestReadWriteProto/uncompressed": 723013 bytes
2018/11/12 20:55:10 Compressed size of "TestReadWriteProto/brotli": 55538 bytes
2018/11/12 20:55:10 Compressed size of "TestReadWriteProto/default": 55537 bytes
2018/11/12 20:55:11 Compressed size of "TestReadWriteProto/brotli,transpose": 32529 bytes
2018/11/12 20:55:11 Compressed size of "TestReadWriteProto/uncompressed,transpose": 581299 bytes
2018/11/12 20:55:13 Compressed size of "TestReadWriteProto/transpose": 32522 bytes
--- FAIL: TestReadWriteProto (0.00s)
    --- FAIL: TestReadWriteProto/zstd (0.65s)
        riegeli_test.go:204: Read error: proto: can't skip unknown wire type 7
FAIL
```

**Comment by schroederc** [comment]
Weird.  This does not fail in our CI instance: https://buildbot-dot-kythe-repo.appspot.com/#/builders/17/builds/183

**Comment by schroederc** [comment]
It's flaky: `bazel test --runs_per_test_detects_flakes --cache_test_results=no --runs_per_test=10 //kythe/go/util/riegeli:riegeli_test`

**Comment by bzz** [comment]
Thank you for prompt feedback! Confirmed, indeed it passes now.

**Comment by schroederc** [comment]
It's also only flaky when the tests are run in parallel.  This seems to work all the time: `bazel test --runs_per_test_detects_flakes --cache_test_results=no --runs_per_test=500 --test_arg=-test.parallel=1 //kythe/go/util/riegeli:riegeli_test`

**Comment by creachadair** [comment]
> It's also only flaky when the tests are run in parallel

I think that is probably WAI, given that Riegeli doesn't synchronize across multiple writers. We could probably deflake it by choosing a nonce file path per execution, I suppose.

**Comment by schroederc** [comment]
The parallel tests are using separate Riegeli writers/readers on separate `bytes.Buffer`s and the problem only affects the tests using zstd compression.
