### ISSUE TITLE
Usage of KZip extraction for multi-module Maven projects

### ISSUE THREAD

**Issue by c-goetz** [kythe/kythe#3264]
Hi all,

we have a multi-module Maven project and I wanted to change the extraction so that it uses KZip instead of KIndex. The problem I'm experiencing is that the KZip file gets overwritten for each Maven module.
Is this behavior intended? The documentation for KZip implies that it's possible to store multiple compilation units in one KZip.

Thanks for your help (and Kythe in general)
Carlo

**Comment by danielmoy-google** [comment]
Hi Carlo,

Yes indeed that is unsupported right now, but we would like to support it.

You are correct that you can put multiple CU in a single kzip (it's just a zip archive really).

Roughly speaking we're probably looking at modifying [AbstractJavacWrapper](https://github.com/kythe/kythe/blob/master/kythe/java/com/google/devtools/kythe/extractors/java/standalone/AbstractJavacWrapper.java#L123) to do one of two things differently:

1. output multiple files instead of to a single file (perhaps using KYTHE_OUTPUT_DIRECTORY like the old kindex
1. read in the file first to see if there's something in there, and add more results to it.

There's no right answer there about which way is better to do it.  It is worth noting that the first option there is closer to how the bazel indexer already does things.  Also there might be some advantage to having a unique filename there - I don't suppose we could make a filename based on the hash of the cu like bazel does?  That'd be sweet.

If we do that first option, we would need to build a utility that combines multiple kzip - but we already need such a library for bazel extraction on google cloud build anyways, so that won't be extra work.

**Comment by c-goetz** [comment]
I would prefer the first variant. We make use of Mavens parallel builds. Writing concurrently to the same zip-archive does not sound like fun.

Would the following changes to the extractor be ok?
- check if `KYTHE_KZIP` is set to non-empty value (like `KYTHE_INDEX_PACK`)
- if so write kzips to `KYTHE_OUTPUT_FILE` folder

For merging there is zipmerge from libzip (https://libzip.org/documentation/zipmerge.html).

Are there any pointers to setting up a development environment (preferably IntelliJ) or is it straight forward (never worked with bazel)?

**Comment by shahms** [comment]
zipmerge should "just work" depending on how it deals with conflicting files.  All of the extractors currently use the same root directory (called "root") although this isn't required by the spec (so could conceivably result in invalid .kzip files).

**Comment by creachadair** [comment]
Unfortunately `zipmerge` doesn't quite work because it does not merge the contents of the index wrappers. However, if you know that your index wrappers are all empty, you can safely do that.

**Comment by danielmoy-google** [comment]
So some update here, currently we are leaning towards having extractors produce multiple kzips and then just uploading them separately.

**Comment by danielmoy-google** [comment]
@c-goetz, did you have an open source project that we should include in testing as we build out support in the future, or is it an internal thing?

**Comment by shahms** [comment]
That's going to be pretty terrible from a bandwidth perspective :-(

**Comment by danielmoy-google** [comment]
Yea.  Also cody just pointed out to me that downstream we prefer to have everything in a single kzip, so nevermind there.  zipmerge it is

**Comment by schroederc** [comment]
> Unfortunately `zipmerge` doesn't quite work because it does not merge the contents of the index wrappers. However, if you know that your index wrappers are all empty (or all consistent), you can safely do that.

We're talking about indexing a single corpus at a single revision so we have consistency and `zipmerge` should be fine.

**Comment by c-goetz** [comment]
@danielmoy-google sadly it's an internal project. I have an example project with the same structure flying around from my first experiments with Kythe.
If it helps I could clean it up and push it to Github.

**Comment by danielmoy-google** [comment]
Sure, if it reasonably mirrors what you'll need internally, it should work for testing.

**Comment by danielmoy-google** [comment]
Also we'll be testing with guava:

https://github.com/google/guava/blob/master/pom.xml#L63

Since right now we're just extracting the main guava directly, instead of supporting modules properly.

**Comment by danielmoy-google** [comment]
Anyways, @c-goetz see if the changes from #3298 are working for you (note you'll need to set `KYTHE_OUTPUT_DIRECTORY`, not `KYTHE_OUTPUT_FILE` or whatever).  It's working for me on guava, but I can't test your internal repo.

Steps for making this work with guava were basically:

* download guava repo
* modify some `pom.xml` files (actually the top-level one already has the compiler-plugin, but some of the lower ones need details), there's the gcr.io/kythe-public/build-preprocessor docker image that can do this for you, or there's the underlying binary you can run at `kythe/go/extractors/config/preprocessor`.
* copy down the necessary extractor artifacts (they're stored in `/opt/kythe/extractors` folder in gcr.io/kythe-public/kythe-javac-extractor-artfiacts if you just want to copy them over from docker, or you can chase down the locations yourself from the Dockerfile spec in `kythe/java/com/google/devtools/kythe/extractors/java/artifacts` - there's two files to copy from the repo, and you'll have to build the javac_extractor_deploy.jar yourself and copy that over
* then run

```
KYTHE_CORPUS=guava TMPDIR=~/test/guava/logs KYTHE_ROOT_DIRECTORY=$HOME/code/guava KYTHE_OUTPUT_DIRECTORY=~/test/guava/full-out JAVAC_EXTRACTOR_JAR=~/test/extractor-artifacts/javac_extractor_deploy.jar KYTHE_JAVA_RUNTIME_OPTIONS=-Xbootclasspath/p:~/test/extractor-artifacts/javac-9-dev-r4023-1.jar REAL_JAVAC=`which javac` mvn -e clean compile -Dmaven.compiler.forceJavacCompilerUse=true -Dmaven.compiler.fork=true -Dmaven.compiler.executable=~/test/extractor-artifacts/javac-wrapper.sh
```

Just run that from the top level guava repo and you should get a few separate kzips for different parts :)

As mentioned in the above comment, I will clean this up so we can just run a GCP on a repo with multiple pom.xml, but if you want to check if it should work for you the above should be a decent guideline of testing extraction.

**Comment by c-goetz** [comment]
I just tried it with our project.
The project is structured like this:
```
.
├── project
│   ├── module-a
│   │   ├── pom.xml
│   ├── module-b
│   │   ├── pom.xml
│   ├── parent
│   │   ├── pom.xml
```
Each module is declared in `parent/pom.xml` like this:
```.xml
<modules>
  <module>../module-a</module>
  <module>../module-b</module>
</modules>
```
In `parent/pom.xml we declare a build profile for kythe:
```.xml
<profiles>
  <profile>
    <id>kythe</id>
    <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
	<inherited>true</inherited>
	<configuration>
	  <fork>true</fork>
	  <executable>${env.JAVAC_WRAPPER}</executable>
	</configuration>
      </plugin>
    </plugins>
    </build>
  </profile>
</profiles>
```
Running the build profile with the env-vars set, leads to multiple kzips in the `KYTHE_OUTPUT_DIRECTORY`. So everything works.
Thanks!
