### ISSUE TITLE
Bazel extraction for golang has the corpus hardcoded to `kythe.io`

### ISSUE THREAD

**Issue by achew22** [kythe/kythe#3270]
Looking at the source for the [bazel_go_extractor extra_action](https://github.com/kythe/kythe/blob/master/kythe/go/extractors/cmd/bazel/BUILD#L26) (as of commit a4e96aac80d3e55e79ad3aaed441f938e30862dc) it appears that the corpus is hardcoded to `kythe.io`. Is there a preferred way of overriding that? I tried messing with the [kythe_config.json](https://github.com/kythe/kythe/blob/a4e96aac80d3e55e79ad3aaed441f938e30862dc/kythe/examples/bazel/kythe_config.json) but I couldn't find a path in the build graph to the bound source at `//external:vnames_config`. The best theory I have is that it is probably possible to patch the kythe repo using `http_archive`, but it feels like there is probably a better way.

Thanks so much!

**Comment by creachadair** [comment]
My general expectation is that if you're using Bazel to extract for a repo _other_ than Kythe, you'd write your own `extra_action` rule in a BUILD file in that repo. Which isn't to say there isn't another solution, but that's why it's written that way now.

**Comment by achew22** [comment]
That seems reasonable to me. Looking in that file, is it possible then to expand the visibility of [the extractor](https://github.com/kythe/kythe/blob/master/kythe/go/extractors/cmd/bazel/bazel_go_extractor/BUILD#L5) beyond `//kythe:default_visibility`?

**Comment by achew22** [comment]
Also, is corpus something that should be passed in? Isn't that the purpose of the [govnames.json](https://github.com/kythe/kythe/blob/master/kythe/go/extractors/cmd/bazel/govnames.json) file?
