### ISSUE TITLE
Eliminate com_google_protobuf build customizations

### ISSUE THREAD

**Issue by schroederc** [kythe/kythe#3272]
Kythe has a clone of protobuf's BUILD file for its own customization.  However, the customizations make it difficult for Kythe to be introduced as a Bazel external repository to projects (like Bazel) that use the vanilla protobuf build.

**Comment by creachadair** [comment]
I think the original motivations for this were to (a) inject a rule for zlib, and (b) fix some C++ compiler flags that aren't compatible with the Kythe build. The latter was the one I couldn't find a way around without changes upstream.

**Comment by schroederc** [comment]
https://github.com/protocolbuffers/protobuf/pull/5389 is one way of eliminating our zlib customization.

I haven't found any flag incompatibilities with protobuf at HEAD other than an issue with `-fno-rtti` that we can probably fix upstream.

**Comment by creachadair** [comment]
+1. I don't think there's any reason to _not_ fix it upstream if they'll actually take the change.

**Comment by shahms** [comment]
Yeah, it was primarily `a` AFAIK.  The proposed PR would require us to build with `--define=protofbuf_zlib` which :-(

I think you could revise it to:
```
select({
  '@//:use_zlib': _ZLIB_OPTS,
 '//conditions:default': [],
})
```
which would allow enclosing projects to define the config setting themselves, rather than relying on `--define`
