### ISSUE TITLE
java indexer should emit tag/deprecated facts

### ISSUE THREAD

**Issue by jaysachs** [kythe/kythe#3279]

**Comment by zrlk** [comment]
This might be as simple as checking for Flags.DEPRECATED (http://google3/third_party/java_src/jdk/openjdk8/u60/trunk/langtools/src/share/classes/com/sun/tools/javac/code/Flags.java?l=116&rcl=139963081) on e.g. classDef.mods.flags. We'd have to make sure that gets set for all combinations of the @Deprecated annotation and the @deprecated Javadoc tag.
