### ISSUE TITLE
Documentation for ref/file has ref/expands/transitive example

### ISSUE THREAD

**Issue by kamahen** [kythe/kythe#3302]
It appears that the example for ref/expands/transitive got put with ref/file and there's no ref/file example
https://kythe.io/docs/schema/#refexpandstransitive
https://kythe.io/docs/schema/#reffile

Apparently this was done for issue #2448 (and nobody has noticed the missing example for ref/file)

**Comment by salguarnieri** [comment]
That was fixed by #3261. I just pushed the updates to the live website.
