### ISSUE TITLE
Add instructions for build setup on macOS

### ISSUE THREAD

**Issue by creachadair** [kythe/kythe#3313]
The steps to get a working Kythe build setup on macOS are sufficiently different from Linux-based systems that I think they deserve a separate document. 

I propose to write this doc, based on my [recent experience](https://gist.github.com/creachadair/3d652f8259d14daca9985dbf00915581) of setting it up.

One question, though: Assuming you agree this is worth doing, would you like it to be inlined into the existing [Getting Started doc](kythe/web/site/getting-started.md), or put into a separate file and linked? The latter would be my preference, but I don't feel very strongly about it.

**Comment by salguarnieri** [comment]
Thanks for doing this!

I'd prefer a separate file.

**Comment by danielmoy-google** [comment]
Agree with latter (separate file)

**Comment by salguarnieri** [comment]
After #3316 I'll push the website and close this issue

**Comment by salguarnieri** [comment]
The website should be live now.
