### ISSUE TITLE
Unable to build on macOS after #3308

### ISSUE THREAD

**Issue by creachadair** [kythe/kythe#3324]
Since submission of #3308, I am no longer able to successfully run `bazel test //kythe/...` on macOS. Previously it worked, as of commit 3ecd75c3 (use the repro instructions below, _mutatis mutandis_).

## Repro

```sh
$ git checkout master
$ git pull
$ git checkout -b repro 434c0b0f
$ rm -vfr third_party/llvm/llvm  # N.B.- will force an LLVM rebuild, get coffee
$ ./tools/modules/update.sh
$ bazel test //kythe/...
```

## Expected

Build and successfully execute tests.

## Observed

```
ERROR: $HOME/software/kythe/tools/modules/BUILD:21:1: Executing genrule //tools/modules:check_modules failed (Exit 1)
Missing LLVM with ancestor 3fe1b12fca949399a3334a072ee7f96e2b6f557e (rev 345798) in third_party/llvm/llvm
Please run ./tools/modules/update.sh.
INFO: Elapsed time: 2.906s, Critical Path: 0.35s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

But note:

```
$ ls third_party/llvm/llvm/*.sentinel
third_party/llvm/llvm/3fe1b12fca949399a3334a072ee7f96e2b6f557e.sentinel
```

**Comment by danielmoy-google** [comment]
Ah yea I only tested this on linux, dunno if I have access to a mac to test this on.

**Comment by danielmoy-google** [comment]
Nvm I can repro this on linux as well.  Unsure why I couldn't repro it before.

**Comment by danielmoy-google** [comment]
so `check_repo` is assuming we're still in git land:

https://github.com/kythe/kythe/blob/master/tools/modules/check.sh#L28

I guess we could check for the sentinel and enforce the exact version.  Not the greatest solution, but if we're checking out only the shallow zip that might be the best solution.

**Comment by danielmoy-google** [comment]
@creachadair try #3326 (is working for me on my repro, but not mac so I'm not sure)
