### ISSUE TITLE
Add support for Go modules in the Go extractor

### ISSUE THREAD

**Issue by creachadair** [kythe/kythe#3334]
Go 1.11 added support for a new package organization scheme called "modules", and subsequent versions will extend this (see https://blog.golang.org/modules2019) with the goal of replacing the existing `GOPATH` mechanism by the end of 2019. 

The "native" Go extractor should be able to extract compilation records from module builds, even if a `GOPATH` is not available. At minimum this will probably require integrating with the [golang.org/x/tools/go/packages](http://godoc.org/golang.org/x/tools/go/packages) package, and possibly some other shenanigans.

**Comment by schroederc** [comment]
Duplicate of #2881

**Comment by creachadair** [comment]
Oops, sorry I missed the earlier one.
