### ISSUE TITLE
go mod issue unexpected module path "kythe.io"

### ISSUE THREAD

**Issue by yinheli** [kythe/kythe#3344]
parsing go.mod: unexpected module path "kythe.io"

**Comment by creachadair** [comment]
In order that we may be able to help, can you please add some more details about what you were trying to do when you encountered this error? E.g., what command did you run, and in what environment?

Among other things, it would also help to know your OS, Go version, what release and/or commit of Kythe you have checked out, and any other useful information you can provide.

**Comment by glaslos** [comment]
go version go1.11.4 linux/amd64
```
> go mod init github.com/you/hello
> go get github.com/kythe/kythe

go: finding github.com/kythe/kythe v0.0.29
go: github.com/kythe/kythe@v0.0.29: parsing go.mod: unexpected module path "kythe.io"
go: error loading module requirements
```

**Comment by glaslos** [comment]
What actually works is `go get kythe.io@master`

**Comment by glaslos** [comment]
Seems like one issue is that you have to specify a version/branch:
```
⟩ go get kythe.io/kythe
go: finding kythe.io/kythe latest
go get kythe.io/kythe: no matching versions for query "latest"
```

**Comment by creachadair** [comment]
`go get` generally wants an import path, not a module name—a module name may or may not match the name of a package. `go get kythe.io/kythe/go/platform/kzip` (for example) should work.

**Comment by glaslos** [comment]
Ah, thanks for the pointer. So it turned out the main issue was an old import `"github.com/google/kythe/kythe/go/platform/delimited"` which causes the initial error. Replacing all old imports like `"kythe.io/kythe/go/platform/delimited"` resolves the problem for me.
