### ISSUE TITLE
Support multiple goal prefixes in Kythe verifier

### ISSUE THREAD

**Issue by shekhawatk** [kythe/kythe#3345]
Currently Kythe verifier supports only one goal prefix. I need to write test for cross language linking. The languages in this case have different comment prefixes. E.g. // and #.

**Comment by justbuchanan** [comment]
You should be able to work around this by using `--goal_regex` instead of `--goal_prefix`. See the docs at https://kythe.io/docs/kythe-verifier.html#_specifying_goals.

For your case, something like `--goal_regex "\s*(?:#|(?://))\-(.*)"` should work.

**Comment by shekhawatk** [comment]
I have tried specifying the regex like this. It seems the verifier does not
support two goal specifiers. I have got this error message:

"Wrong number of capture groups in goal comment regex"
"want 1"

Please check.

Thanks,
Kuldeep

**Comment by shahms** [comment]
You need to use non-capturing groups except for the goal text.  What @justbuchanan wrote should mostly work (but has some unbalanced parens), does:

`"\s*(?:#|//)-(.*)` work?

**Comment by shekhawatk** [comment]
Thanks a lot, @shahms and @justbuchanan! This worked.
