### ISSUE TITLE
Kythe build fails in read-only filesystem

### ISSUE THREAD

**Issue by kamahen** [kythe/kythe#3395]
Bazel is designed to work with a read-only file system, but there are at least two places where the Kythe build requires r/w directories:

- `kythe/third_party/llvm`,`tools/build_rules` (when running `tools/modules/update.sh`)
- `kythe/web/ui` (when building `//kythe/web/ui`)

In the case of `//kythe/web/ui`, there are `tags=["manual"]` options, but no explanation. By grepping through the source tree, I found about 40 other instances of `"manual"` tags, some with `"local"`.

This issue is being opened to preserve some knowledge I picked up while debugging why `http_server` wasn't working properly for me (part of the reason was that `//kythe/web/ui` is a manual rule). Pull #3393 partially adds documentation about this, but without explanation for the `"manual"` tag. (There is also some discussion in issue #1725, which doesn't belong there.)

**Comment by shahms** [comment]
This has been fixed (although there are unrelated issues with kythe/web/ui)
