### ISSUE TITLE
Documentation is only written by beam postprocessor, but not by stock write_tables.

### ISSUE THREAD

**Issue by robinp** [kythe/kythe#3412]
With a stock serving table, `kythe docs` invocation (or the corresponding `xrefs.Documentation` call) doesn't return any results, while the `/kythe/edge/documents` and the target `doc` node seems to be present.

On inspecting the code, the "docs:" key prefix is only mentioned in the `beam` processor. Indeed, running
```
$ bazel-bin/kythe/go/serving/tools/write_tables/write_tables \
    --entries /tmp/entries --experimental_beam_pipeline --out /tmp/bktab
```                                                                                                   
produces a serving table capable of serving docs.

```
$ ./bazel-bin/kythe/go/util/tools/scan_leveldb/scan_leveldb /tmp/bktab/ |awk '{print $1}'| cut -d: -f1 | sort | uniq -c                                                                              
   1121 "decor
    659 "dirs
  13795 "docs
 939942 "edgeSets
 130931 "xrefs

$ ./bazel-bin/kythe/go/util/tools/scan_leveldb/scan_leveldb /tmp/ktab/ |awk '{print $1}'| cut -d: -f1 | sort | uniq -c                                                                       
   1121 "decor
    659 "dirs
     25 "edgePages
 940132 "edgeSets
     25 "xrefPages
 136821 "xrefs

```
Is this intended? Is `beam` the suggested postprocessor to use?

**Comment by creachadair** [comment]
Ideally both should produce compatible results, but I think right now beam is getting the most attention and it reflects a number of more recent schema developments. I would recommend using beam for now, both because it is likely to be more up-to-date and because we'd like feedback and bug reports on it. :)

**Comment by robinp** [comment]
Thank you!
