### ISSUE TITLE
macOS build fails at commit 5fe57f02

### ISSUE THREAD

**Issue by creachadair** [kythe/kythe#3439]
Commit 5fe57f026138f7df4cedec0d389b28f757e36142 appears to have broken the macOS build:

```
$ bazel test kythe/go/...
[…]
INFO: Invocation ID: 45240d9e-4e8b-493b-9032-280fc8f62f0a
INFO: Build option --run_under has changed, discarding analysis cache.
ERROR: /private/var/tmp/_bazel_michael/4ad4e77a574cde1e20a887307ff11f34/external/local_config_cc/BUILD:58:5: in apple_cc_toolchain rule @local_config_cc//:cc-compiler-tvos_x86_64: Xcode version must be specified to use an Apple CROSSTOOL. If your Xcode version has changed recently, try: "bazel clean --expunge" to re-run Xcode configuration
ERROR: Analysis of target '//kythe/go/util/tools/print_test_status:print_test_status' failed; build aborted: Analysis of target '@local_config_cc//:cc-compiler-tvos_x86_64' failed; build aborted
INFO: Elapsed time: 1.393s
INFO: 0 processes.
ERROR: Couldn't start the build. Unable to run tests```
```

I tried following the suggestion in the log message, running `bazel clean --expunge` and retrying the build, but I got the same error.

Diagnostics:

```
$ bazel version
INFO: Invocation ID: d890a6fd-44e4-4d18-8c49-36ca31e21ddf
Build label: 0.22.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jan 28 13:00:18 2019 (1548680418)
Build timestamp: 1548680418
Build timestamp as int: 1548680418
gorion:kythe michael$ uname -a
Darwin gorion.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```

**Comment by creachadair** [comment]
> Have you tried the steps in https://kythe.io/getting-started/#troubleshooting-bazelclangllvm-errors?

Most of those instructions are obsolete (they still refer to `update.sh` and Clang 3.5, for example), but I did do `bazel clean --expunge` and rebuilt fresh. Also I was able to build fine just prior to this commit.

**Comment by schroederc** [comment]
In particular, have you tried setting the `CC` environment variable to the path of your clang installation?

**Comment by creachadair** [comment]
> In particular, have you tried setting the `CC` environment variable to the path of your clang installation?

I tried `env CC=/usr/bin/clang bazel test //kythe/...` but got the same error. This looks to me like a select issue somewhere in the toolchain rule, particularly given @shahms's observation that the message mentions tvOS.

**Comment by creachadair** [comment]
I also tried `bazel build --client_env=CC=/usr/bin/clang //kythe/...` (which is where my clang lives).

```
$ clang --version
$ clang --version
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by creachadair** [comment]
Added https://github.com/kythe/kythe/issues/3441 for the doc issue.

**Comment by schroederc** [comment]
This was noticed on the affected machine:

```
$ env -i xcrun xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

This command fixed the issue:

```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

**Comment by creachadair** [comment]
I should add that to our setup docs, since the Bazel instructions only specify that the command-line tools are required, but seem to implicitly want more.

**Comment by Becy2015** [comment]
bazel clean --expunge && bazel build @local_config_cc//:toolchain  solved my problem.
