### ISSUE TITLE
Trying to extract cgo when cxx_extractor is active yields trying to build odd archs

### ISSUE THREAD

**Issue by robinp** [kythe/kythe#3469]
Not sure if this is Kythe or Bazel, but if you could repro that would at least mean it's not just my setup (which has a fair chance).

```
bazel build -s @go_levigo//... --experimental_action_listener=@io_kythe//kythe/extractors:extract_kzip_go  --experimental_action_listener=@io_kythe//kythe/extractors:extract_kzip_cxx
```
fails with something like
```
SUBCOMMAND: # @go_levigo//:go_default_library%android_386%cgo_codegen [action 'CGoCodeGen @go_levigo//:go_default_library%android_386%cgo_codegen']
....
```
Depending on concurrency, sometimes it is `arm`, or other non-local platforms. This doesn't happen when `extract_kzip_cxx` is not passed to the build invocation.

**Comment by creachadair** [comment]
I am not too surprised, since cgo does use the C compiler. Specifically, the build step does—and I would be fairly surprised if it does _not_ pick up environment variables and other state from the rest of the toolchain, as C++ has very poor isolation.

**Comment by robinp** [comment]
@creachadair but why would the toolchains used vary based on presence of `--experimental_action_listener=@io_kythe//kythe/extractors:extract_kzip_cxx`? Without the cxx extractor, only the right toolchain is used.

Maybe you mean that the cxx extractor depends on some toolchains, and those get picked up by cgo as well?

**Comment by creachadair** [comment]
Yes, that's what I mean.

**Comment by shahms** [comment]
Combined with the fact that cgo doesn't play particularly well with containing build systems, it's not terribly surprising there is an issue here.

I can reproduce this, so it's not just your set up.

**Comment by creachadair** [comment]
At least as of a few months ago, I know that there was some discussion about how to improve cgo operability in the Bazel rules, but I don't know the current status. The docs do say:

> If your project includes cgo code, has C/C++ dependencies, or requires external linking, you'll need to write a CROSSTOOL file for your toolchain and set the --cpu flag on the command line, in addition to setting --platforms. You'll also need to set pure = "off" on your go_binary. We don't fully support this yet, but people have gotten this to work in some cases.

Have we done that? (I couldn't find one, so I am guessing we might be using some defaults)

**Comment by shahms** [comment]
https://github.com/bazelbuild/rules_go/blob/8670623e6e3a18123129173ba667c33631aca006/go/private/rules/cgo.bzl#L518 generates cgo for all of the platforms specified in https://github.com/bazelbuild/rules_go/blob/master/go/platform/list.bzl

It looks like there is intended to be some config_setting selection there, but perhaps that has been broken.

We did have a custom CROSSTOOL, but not so much for cgo as for Clang/LLVM.  Cody switched that to use the default in 5fe57f026138f7df4cedec0d389b28f757e36142

**Comment by shahms** [comment]
Regardles, it *looks* like this is a known bug in the Go rules rather than Bazel or Kythe, specifically.

**Comment by schroederc** [comment]
https://github.com/bazelbuild/rules_go/issues/1821

Using `--experimental_extra_action_top_level_only` avoids running the extraneous Go actions.

**Comment by robinp** [comment]
Works great, thanks!
