### ISSUE TITLE
cxx extractor should error out if a #include is not found

### ISSUE THREAD

**Issue by justbuchanan** [kythe/kythe#3504]
I noticed that the extractor exits "successfully" with code zero even if errors are encountered during extraction. Should it error out instead?

As an example, here's what I see in bazel when I attempt to build a kzip that doesn't have all its dependencies:

```console
$ bazel build //kythe/cxx/indexer/cxx/testdata/proto:proto_genlang_kzip
INFO: Analysed target //kythe/cxx/indexer/cxx/testdata/proto:proto_genlang_kzip (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: From ExtractCompilation kythe/cxx/indexer/cxx/testdata/proto/proto_genlang_kzip/proto.cc.kzip:
kythe/cxx/indexer/cxx/testdata/proto/proto.cc:1:10: fatal error: 'kythe/cxx/indexer/cxx/testdata/proto/testdata.pb.h' file not found
#include "kythe/cxx/indexer/cxx/testdata/proto/testdata.pb.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Target //kythe/cxx/indexer/cxx/testdata/proto:proto_genlang_kzip up-to-date:
  bazel-bin/kythe/cxx/indexer/cxx/testdata/proto/proto_genlang_kzip/proto.cc.kzip
INFO: Build completed successfully, 2 total actions
```

**Comment by shahms** [comment]
Yes, it seems like it should.  Although some things like this aren't actually errors (failure to find Kythe metadata, for example), this seems like it should be.

**Comment by justbuchanan** [comment]
When would the extractor look for, but fail, to find Kythe metadata? For generated code, shouldn't the #include "my.meta.h" only be present if the corresponding metadata file actually exists?

**Comment by shahms** [comment]
The meta.h file isn't `included` but is mentioned via `#pragma kythe_metadata` which will be present in every header, but it shouldn't be an error if the file is missing from transitive dependencies of that header.

We also want to index the file and accept that we won't get cross-language refs if the metadata is missing.
