### ISSUE TITLE
Serve out of Google Cloud bucket

### ISSUE THREAD

**Issue by achew22** [kythe/kythe#3520]
On the [mailing list](https://groups.google.com/d/topic/kythe/XQ9-aPfyQPs/discussion) I asked:

> It looks like there are a bunch of ways to load the indexed data into a Google Cloud bucket (write_tables has a --entries and --out flag that take a gs:// protocol), but is there a way to serve out of those buckets?

@schroederc says:

>   Not yet.  The current library we use to read the LevelDB files doesn't support non-local filesystems.  It's possible, though, and I encourage you to add a feature request on Github.

**Comment by schroederc** [comment]
https://godoc.org/github.com/syndtr/goleveldb/leveldb#Open would allow us to support serving from GCS.
