### ISSUE TITLE
GCB extraction should echo errors before merging kzip, or have kzip merge cleanly support empty bits

### ISSUE THREAD

**Issue by danielmoy-google** [kythe/kythe#3521]
For example see kythe/extractors/gcp/examples/mvn.yaml

There are classes of errors on extraction for maven/gradle which don't exit from `mvn`/`gradle` build step with an error, but do emit a non-empty `javac-extractor.err`.  However the next step to merge kzip currently fails if there are no .kzip files, so the resulting javac-extractor.err file won't get uploaded.

A simple and potentially sufficient workaround for this would be to just echo out the contents of `javac-extractor.err` (probably `javac-extractor.out` for good measure too, because there are certain classes of errors that show up in the .out file).

Alternatively it might be worth making kzip merge build step not die on empty input (probably the bash isn't written correctly I'd guess).  Then just rely on artifact upload for .err (possibly .out too).

Currently I'm leaning towards the former.

**Comment by jsachs-google** [comment]
What about the kzip step not die silently on empty input? e.g. give a usage?

I like *also* dumping extractor.err to stdout as a step as well.

**Comment by danielmoy-google** [comment]
kzip merge step doesn't die silently on empty input, though if I gather what you're suggesting, it's to make the error message more useful (since right now it only complains about zero kzip files to merge).

Maybe what would make sense is an explicit "print .err/.out, and die if .err is non-zero size or there are no kzips" step in between extract and merge.

**Comment by danielmoy-google** [comment]
The more that I think about it, the more I am of the opinion we should actually have a step after extraction explicitly push .err/.out to a gs bucket, not simply print the error.  Then, don't upload it as an artifact at the end - that way if there's any failure between end of extraction and the end (e.g. merge as prompted by this issue), we'll still get log messages in a reliable place.

I'm still not settled on what to do for errors so bad they crash the extraction step itself - perhaps we just rely on log messages printed out during the course of that failure.

**Comment by danielmoy-google** [comment]
Ok we now echo errors always.
