### ISSUE TITLE
gcp extraction of bazel.googlesource.com/bazel.

### ISSUE THREAD

**Issue by jaysachs** [kythe/kythe#3550]
Successful extracting HEAD of bazel seems to require the most current bazel builder docker image. Since our GCP yaml file uses 'gcr.io/kythe-public/bazel-extractor' as the extracting image, we end up pinned back to earlier versions of the bazel build image. I don't see a way to build a "floating" image base where the base image version is unspecified. So is there some other mechanism we can use? e.g. mount our builder, copy it to a build-persistent volume, and the use it from there to run the bazel builder?

**Comment by jaysachs** [comment]
Understood that sometimes bazel HEAD won't even build then, but I believe (anecdotally) that's less frequent, and a transient situation.

**Comment by danielmoy-google** [comment]
On the other hand, `gcr.io/kythe-public/bazel-extractor` as a literal string is actually not pinned back to earlier (it is if you throw a `:stable` or whatever tag on there), so we could conceivably not pin it, use the latest one, and be careful about it.

**Comment by danielmoy-google** [comment]
It would also require us to be on top of updating bazel-extractor quickly after a new bazel version.

**Comment by jaysachs** [comment]
> It would also require us to be on top of updating bazel-extractor quickly after a new bazel version.

Right. It'd be nice to not have to do this ... I agree that layering with a Docker image is "nicer" but it's more fragile. Note that the Dockerfile would change just moderately ... instead of "adding" all those kythe things, it would simply copy them to the location passed on the cmdline.

**Comment by danielmoy-google** [comment]
The bazel image has a lot of stuff you'd need to copy out though:

https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/bazel/Dockerfile

**Comment by jaysachs** [comment]
I'm suggesting the opposite ... our Dockerfile would just copy the "kythe-y" things out to the volume specified. We'd then extract using the standard bazel build image, using a custom entrypoint.

**Comment by danielmoy-google** [comment]
Ah ok.  That might be doable.  It is sort of close to what we do in maven/gradle (copy out some kythe-specific bits from mounted volumes).

**Comment by schroederc** [comment]
https://github.com/kythe/kythe/pull/3574 supports pulling in the Kythe release archive as a remote repository which will help the custom entrypoint reversal.

**Comment by jaysachs** [comment]
#3596 supports using bazelisk to "dynamically" choose the bazel version.
