### ISSUE TITLE
Build failure with Go 1.12

### ISSUE THREAD

**Issue by creachadair** [kythe/kythe#3551]
At head on macOS with Go 1.12 installed via Homebrew, I get the following error when trying to build:

```
# Some log output elided for brevity.
$ bazel build kythe/go/util/tools/extractschema
ERROR: /Users/michael/software/kythe/kythe/go/util/tools/extractschema/BUILD:5:1: no such package '@org_bitbucket_creachadair_stringset//': no such package '@bazel_gazelle_go_repository_tools//': failed to build fetch_repo: build cache is required, but could not be located: GOCACHE is not defined and $HOME is not defined
 and referenced by '//kythe/go/util/tools/extractschema:extractschema'
ERROR: Analysis of target '//kythe/go/util/tools/extractschema:extractschema' failed; build aborted: no such package '@org_bitbucket_creachadair_stringset//': no such package '@bazel_gazelle_go_repository_tools//': failed to build fetch_repo: build cache is required, but could not be located: GOCACHE is not defined and $HOME is not defined
```

I don't think this is specific to macOS, but the error is (slightly) different on Linux:

```
ERROR: /home/kythedev/kythe/kythe/go/util/tools/extractschema/BUILD:5:1: no such package '@org_bitbucket_creachadair_stringset//': no such package '@bazel_gazelle_go_repository_tools//': failed to build fetch_repo: build cache is required, but could not be located: GOCACHE is not defined and neither $XDG_CACHE_HOME nor $HOME are defined
 and referenced by '//kythe/go/util/tools/extractschema:extractschema'
ERROR: Analysis of target '//kythe/go/util/tools/extractschema:extractschema' failed; build aborted: no such package '@org_bitbucket_creachadair_stringset//': no such package '@bazel_gazelle_go_repository_tools//': failed to build fetch_repo: build cache is required, but could not be located: GOCACHE is not defined and neither $XDG_CACHE_HOME nor $HOME are defined
```

I imagine this is just a configuration issue with the new 1.12 release. "And yet it fails".

**Comment by danielmoy-google** [comment]
I agree it is not specific to macOS.  The error message will vary each time you run.

I'm not sure what bazel does here, because GOCACHE is definitely set on my go env.

**Comment by shahms** [comment]
#3548 updated the Go build rules to 0.17.1; does it work with 0.17?

**Comment by creachadair** [comment]
> #3548 updated the Go build rules to 0.17.1; does it work with 0.17?

I reverted ec915850 (the commit that made that switch) locally, and am able to build again. It looks like 0.17.1 also brought along Go 1.12, which I suspect is the trigger here. I am not sure how to override which Go version the rules require, though.

**Comment by creachadair** [comment]
Oddly, `@io_bazel_rules_go//go/toolchain/toolchains.bzl` appears to define `DEFAULT_VERSION = "1.11.5"`, so I am not sure why we are picking up Go 1.12 at all in that configuration. Maybe this has something to do with the special magic we're doing at https://github.com/kythe/kythe/blob/ec915850120bc7acae9d09f92646d51056f285bf/WORKSPACE#L25?

**Comment by creachadair** [comment]
The [release notes for v0.17.1](https://github.com/bazelbuild/rules_go/releases/tag/0.17.1) say that

> Starting in this version, def.bzl now references a compatibility repository declared in go_rules_dependencies, so loading def.bzl before calling go_rules_dependencies will result in an error. This is necessary to support older and newer versions of Bazel across breaking Bazel API changes.

So I thought maybe our load-order gag might be tripping on this, and went looking for the target of

```python
load("@io_bazel_rules_go//go/private:compat/compat_repo.bzl", "go_rules_compat")
```

but cannot find that file anywhere. Surely I'm doing something wrong, or else this would be an error during the Load/Analysis phase, right?
