### ISSUE TITLE
Lookup error when using the sample UI

### ISSUE THREAD

**Issue by pedrobisp** [kythe/kythe#3593]
After running the sample ui, I try to explore a corpus by clicking on it, however the following error occurs:

`"look up error: proto unmarshall error: proto: can't skip unknown wire type 4"`

The serving tables were generated by doing the following steps:

```
$/opt/kythe/extractors/go_extractor -v -corpus test -output bson.kzip -bydir $GOPATH/src/gopkg.in/mgo.v2/bson
$/opt/kythe/indexers/go_indexer bson.kzip > entries
$/opt/kythe/tools/write_entries --graphstore leveldb:graphstore < entries
$/opt/kythe/tools/write_tables --graphstore graphstore --out serving
$/opt/kythe/tools/http_server --public_resources /opt/kythe/web/ui/ --listen localhost:8080 --serving_table serving
```

**Comment by schroederc** [comment]
Associated forum post: https://groups.google.com/d/msg/kythe/slTWs02hrI8/lf49jrHcCQAJ

I can confirm this happening on `master`.  However, https://github.com/kythe/kythe/releases/tag/v0.0.30 works end-to-end.

**Comment by schroederc** [comment]
#3603 and #3604 fixes the server and sample web UI's filetree implementation.

Note: #3600 means that the sample web UI won't be part of the release archive right now
