### ISSUE TITLE
All `tapp`s for functions should specify a receiver on `param.2`

### ISSUE THREAD

**Issue by schroederc** [kythe/kythe#3613]
All `tapp` nodes for a `fn` builtin should have at least 3 `param` edges with `param.0` being the language-specific `fn` constructor builtin, `param.1` being the function's return type (possible being a language-specific "void" type), `param.2` being the functions receiver type (possibly being a language-specific "empty" receiver type), and all subsequent `param.N` edges are the function's formal parameter types.

Go example:

```
//- @S defines/binding S
type S struct {}

//- @F defines/binding F
//- F typed FType
//- FType.node/kind tapp
//- FType param.0 FnBuiltin
//- FType param.1 BoolBuiltin
//- FType param.2 S
//- FType param.3 IntBuiltin
func (S) F(a int) bool { return false }

//- @G defines/binding G
//- G typed GType
//- GType.node/kind tapp
//- GType param.0 FnBuiltin
//- GType param.1 BoolBuiltin
//- GType param.2 EmptyTuple
//- GType param.3 IntBuiltin
func G(a int) bool { return false }
```

**Comment by creachadair** [comment]
This seems like a generally good idea. Maybe instead of "EmptyTuple" we could borrow the name "void" here? An empty tuple is more like a unit type than an uninhabited type, though maybe that doesn't matter too much.

More importantly, though, it'd be nice to share that across languages.

**Comment by schroederc** [comment]
I agree that it would be nice to share builtin nodes like the "empty" receiver type.  For now, all builtins are language-specific in Kythe so the first pass of this feature will follow that trend and will probably use `EmptyTuple` instead of inventing a new builtin.  Later on, I would like to look into possibly unifying builtin nodes.

**Comment by creachadair** [comment]
In retrospect, we should probably have added this to the schema before we started changing indexers—but in any case, we should do that.

**Comment by schroederc** [comment]
Schema documentation updated in #3628.
