### ISSUE TITLE
incorrect escaping in web ui

### ISSUE THREAD

**Issue by nnorwitz** [kythe/kythe#3625]
When selecting an item for a cross reference, the top line of the bottom pane where the definitions, declarations, and references are shows something like:  kythe:?lang=c%2B%2B?path=foo/bar.h#V%2FrptxjJiN90TQfl8yoLYH5kmoIPm8%2BplQfZPPqL90w%3D

I expect this is meant to be human readable and the language should at least show as c++ rather than c%2B%2B.  I'm not sure about what should be shown after the #.

**Comment by creachadair** [comment]
That string is a [Kythe URI](https://kythe.io/docs/kythe-uri-spec.html), and it's correctly encoded as far as I can tell, but I agree that it's probably not the most intuitive thing to print out in the UI. The sample UI is intentionally a little skeletal in this regard.
