### ISSUE TITLE
extract_compile_command fails with --distinct_host_configuration=false

### ISSUE THREAD

**Issue by kentsommer** [kythe/kythe#3699]
When using `--distinct_host_configuration=false` it looks like trying to extract compile commands through an `--experimental_action_listener` fails due to a dependency cycle. 

```
kentsommer@X:~/worktrees/compile_db/src$ bazel build --compiler=clang --experimental_action_listener=//tools/compile_commands:extract_json $(bazel query 'kind(cc_.*, //...)')
# Disk cache enabled (/home/kentsommer/.cache/test-bazel-cas)
Starting local Bazel server and connecting to it...
INFO: Invocation ID: a0a75dcf-c7f2-485e-8960-a6b3128459e4
Loading: 502 packages loaded
# Disk cache enabled (/home/kentsommer/.cache/test-bazel-cas)
INFO: Invocation ID: 1d58110f-ae27-445d-9031-efc7527a374d
ERROR: /cache-pool/test-bazel/bazel/_bazel_kentsommer/cfc0e4ecd2274e63a55c4db65b7afe4e/external/bazel_tools/platforms/BUILD:78:1: in platform rule @bazel_tools//platforms:host_platform: cycle in dependency graph:
    //tools:config_ubsan
.-> @bazel_tools//platforms:host_platform
|   @bazel_tools//platforms:osx
|   @bazel_tools//platforms:os
|   //tools/compile_commands:extract_json
`-- @bazel_tools//platforms:host_platform
```

Due to some long-running genrules, I would prefer to not split up the configurations (which does fix the issue but adds a lot of time to the build). Am I overlooking a simple fix to get around this?

Was unsure if this is a question for the core `bazel` team or `kythe`. If here is not the correct place just let me know.

**Comment by justbuchanan** [comment]
To clarify, should that be `//kythe/cxx/tools/generate_compile_commands:extract_json` instead of `//tools/compile_commands:extract_json`?

One flag we almost always use with bazel extra_actions is `--experimental_extra_action_top_level_only` which ensures the extra actions run only on the targets you specify and not on all their dependencies. This might be what you're looking for here.

**Comment by kentsommer** [comment]
Rather than integrate all of Kythe into my bazel project to test this method I opted to temporarily pull in only the pieces I needed. So, the implementation is identical, just living in a slightly different place.

I have tried `--experimental_extra_action_top_level_only` but unfortunately analysis still fails with a detection of the same cycle.

**Comment by creachadair** [comment]
Since `//tools/compile_commands:extract_json` has other dependencies, I am guessing you are trying to build it, which is likely to pull in most of Kythe anyway. I think if you want this to work you'll probably need to check in a compiled binary of the extractor (and make your `extra_action` rule depend on it).

**Comment by kentsommer** [comment]
The dependencies for it are ~minimal and it builds and runs (outside of the `extra_action` rule) fine.
```
 cc_binary(
     name = "extract_compile_command",
     srcs = ["extract_compile_command.cc"],
     deps = [
         "//tools/compile_commands/proto:extra_actions_base_cc_proto",
         "@gflags//:gflags",
         "@glog//:glog",
         "@com_github_tencent_rapidjson//:rapidjson",
         "@com_google_protobuf//:protobuf",
     ],
 )
```
I've tried having the `extra_action` rule depend on a built binary of `extract_compile_command` but it still fails. It almost looks like adding any `--experimental_action_listener` causes analysis to fail although I guess I haven't actually verified this (will do so now).

**Comment by kentsommer** [comment]
It looks like even something as simple as this causes a cycle so this issue probably has nothing to do with Kythe (sorry about the false positive):

```
action_listener(
    name = "echo_listener",
    extra_actions = [":echo_action"],
    mnemonics = ["CppCompile"],
    visibility = ["//visibility:public"],
)

extra_action(
    name = "echo_action",
    cmd = "echo hello > $(output $(ACTION_ID).txt)",
    out_templates = ["$(ACTION_ID).txt"],
)
```

**Comment by creachadair** [comment]
Unfortunately one of the dependencies is `cc_library`, which is far from minimal, and has a lot of deep hooks into the way Bazel works. I don't know exactly why it causes a cycle in this particular context, though.

**Comment by kentsommer** [comment]
@creachadair I'm not sure I understand the `one of the dependencies is cc_library` comment. Are you saying that the implementation of `extract_compile_command.cc` has that dependency? If that is the case (and the cause of the failure), I wouldn't expect the example I gave to fail (which it does). I think I am likely misunderstanding.

**Comment by creachadair** [comment]
> @creachadair I'm not sure I understand the `one of the dependencies is cc_library` comment. Are you saying that the implementation of `extract_compile_command.cc` has that dependency? If that is the case (and the cause of the failure), I wouldn't expect the example I gave to fail (which it does). I think I am likely misunderstanding.

I mean that the rules also introduce dependencies, particularly on the toolchain. This often triggers issues with building in host configuration, though maybe not in this case. So no, I don't mean that our own code depends on it, but that the rule itself also affects the dependency graph. For C++ in particular, there is a lot of Google3 legacy hanging around in the `cc_*` rules.

**Comment by kentsommer** [comment]
:+1: Thanks for clarifying.

**Comment by kentsommer** [comment]
For anyone that stumbles across this, I've opened a bug against the `bazel` project here: https://github.com/bazelbuild/bazel/issues/8080
