### ISSUE TITLE
Links to WebUI in docs are broken

### ISSUE THREAD

**Issue by endobson** [kythe/kythe#3752]
The page https://kythe.io/docs/exploring-kythe-sample-web-ui.html has links to urls like https://xrefs-dot-kythe-repo.appspot.com/#kythe/java/com/google/devtools/kythe/util/JsonUtil.java?line=36 and https://xrefs-dot-kythe-repo.appspot.com/#kythe/cxx/common/CommandLineUtils.h?line=61

These are broken because they are missing the `corpus=kythe` parameter.

**Comment by shahms** [comment]
Deploying now, but my manual tests verify the fix.
