### ISSUE TITLE
Kythe doesn't build with development build of Bazel

### ISSUE THREAD

**Issue by hlopko** [kythe/kythe#3757]
Hello dear Kythe,

I see Kythe implements a Bazel version check, but this doesn't work with the development build of Bazel which we use on our downstream pipeline (https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/989#a722f124-2b90-4559-a939-7c6dd6d921dd). The build is green with the released version of Bazel, it's the only empty version string of development Bazel build that causes trouble.

Thanks!

**Comment by shahms** [comment]
Thanks! This is a known issue (I commented on it in some of the earlier bugs about adding us to the Bazel CI).  I'll try and tackle it today.

**Comment by hlopko** [comment]
Oh that would be great, thanks! I'll then keep Kythe enabled on downstream. Pls let me know if you couldn't get to it, and I'll temporarily disable Kythe then (we need to make sure downstream is green or red only because of our regressions because otherwise devs quickly learn to ignore the pipeline :).

Thanks!

**Comment by shahms** [comment]
@hlopko Let me know if #3760 is not a viable approach.  The other options seem to require making check_version either much more complicated (as a repository_rule) or omitting it altogether (which doesn't lead to particularly user-friendly errors on incompatible changes).

**Comment by hlopko** [comment]
Thanks Shahms! This will do just fine.
