### ISSUE TITLE
Bazel with incompatible_string_join_requires_strings

### ISSUE THREAD

**Issue by laurentlb** [kythe/kythe#3758]
The flag `--incompatible_string_join_requires_strings` will be flipped in Bazel. We've noticed it will break Kythe. I expect this change will be released in Bazel 0.27, to be released in a month.

Logs: https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/115#84672f70-dbb7-4ec7-8d7d-842cfd48423e

Fix: I suspect you just need to update your dependency on rules_go.

**Comment by shahms** [comment]
We need to do that for the `cc_common.configure_features(ctx, ...)` change as well.

**Comment by shahms** [comment]
rules_go has been updated, I can tackle this next

**Comment by achew22** [comment]
@laurentlb was this brought to your attention because of the Bazel CI?

@shahms is it okay that you're going to get issues like this filed against you?

**Comment by shahms** [comment]
Absolutely for me; it beats finding out about them when we get a new version of Bazel pushed to our workstations.  I can't speak for the rest of the developers though :-)

**Comment by shahms** [comment]
It looks like the rules_go update was the only thing required for Kythe
