### ISSUE TITLE
TypeScript indexer: Do not name scopes created by rvalues

### ISSUE THREAD

**Issue by ayazhafiz** [kythe/kythe#3834]
See [this discussion](https://github.com/kythe/kythe/pull/3819#discussion_r294388875) on #3819.

I think we should reconsider how signatures are created for rvalues. In particular, I don't think rvalues should introduce a new scope, since they are anonymous to the lvalues. In a case like

```typescript
class X {
  static y = class Y {
    z: number;
  };
  static a = {
    b: 3;
  };
}
```
Right now, for z, we get a signature of `X.y.Y.z`. For b, it's `X.a.anon0.b` because of the anonymous block.
Ideally, z would have the signature `X.y.z` and b `X.a.b`.

Further complicating this, a code like

```typescript
const a = class A {
  prop = 0;
};
```

Creates a declaration file

```typescript
declare const a: {
    new (): {
        prop: number;
    };
};
```

I'm not sure how to resolve this. The least ambigious answer to me is to give `prop` a signature of `a.prop` in both cases, and we treat the constructor signature `new ()` as an rvalue.

_Edit_: Better explain the issue and proposed solution here.

**Comment by ayazhafiz** [comment]
cc @evmar

**Comment by creachadair** [comment]
Is the following possible?

```ts
class X {
   static y = class Y {
     z: X;
   };
   static z = {
     a: new X(),
   };
}
```

If so, and assuming I correctly understand the goal of collapsing the RHS of the static assignments in the body of `X` so they do not generate intermediate scopes, how will the indexer distinguish 

```ts
console.log(X.y.z);
console.log(X.z);
```

?

(Maybe this isn't legal?)

**Comment by creachadair** [comment]
Actually, in retrospect, maybe that example doesn't show what I was trying to get at, because `y` is static so without an instance I guess `z` won't be reachable. Maybe that's enough to avoid this issue.

**Comment by ayazhafiz** [comment]
> If so, and assuming I correctly understand the goal of collapsing the RHS of the static assignments in the body of `X` so they do not generate intermediate scopes, how will the indexer distinguish
> 
> ```ts
> console.log(X.y.z);
> console.log(X.z);
> ```
> 
> ?

I think in these cases the signatures of `z` would be exactly what is in the console log; that is, `X.y.z` and `X.z` respectively.

The issue is more with the anonymous scope that is currently being created by the block on the RHS of assignments. `z` in `console.log(X.y.z)` currently has a signature of `X.y.Y.z`; only the `Y` is extraneous. Please let me know if my explanation should be better.

> `y` is static so without an instance I guess `z` won't be reachable

True. But even if `z` was static I don't think this would be an issue.
