### ISSUE TITLE
generate Kythe entries from compile_commands.json

### ISSUE THREAD

**Issue by LH-413x** [kythe/kythe#4088]
Hello, 
Can I generate Kythe entries from compile_commands.json directly?

**Comment by shahms** [comment]
It is possible to use `compile_commands.json` to extract kzip files from a given repository, yes.

This sort of question is best directed to our mailing list: https://groups.google.com/forum/#!forum/kythe

**Comment by LH-413x** [comment]
Thanks !

Shahms King <notifications@github.com> 于2019年9月18日周三 上午1:13写道：
