### ISSUE TITLE
Kythe broken by the use of  --incompatible_list_based_execution_strategy_selection

### ISSUE THREAD

**Issue by hlopko** [kythe/kythe#4108]
Hello dear Kythe friends,

I see in https://github.com/kythe/kythe/pull/3817 Kythe fixed a build problem not by migrating to the new behavior, but by unflipping the incompatible flag. This is unsupported (Point 7 in https://docs.bazel.build/versions/0.29.1/backward-compatibility.html). This become a problem now as the flag is removed from Bazel.

I'll have to remove Kythe from Bazel's downstream pipeline until this issue is resolved. Thank you for your understanding.

**Comment by shahms** [comment]
Cody, I think you understand the reasons for this particular flag better than I, but I can take a look at it if you'd prefer.
