### ISSUE TITLE
Cyclic dependency

### ISSUE THREAD

**Issue by ipetr0v** [kythe/kythe#4237]
I'm trying to load Kythe via `bazel sync` and get the following error:

/opt/my-project# bazel sync
ERROR: ErrorInfo{exception=null, rootCauses={}, cycles=[[] -> [[/opt/my-project]/[WORKSPACE], 9, @io_kythe//:external.bzl (in workspace), @io_kythe//tools:build_rules/shims.bzl (in workspace), @io_bazel_rules_go//go:def.bzl (in workspace), @io_bazel_rules_go//go/private:rules/rule.bzl (in workspace), @io_bazel_rules_go//go/private:rules/aspect.bzl (in workspace), @io_bazel_rules_go//go/private:context.bzl (in workspace), @io_bazel_rules_go_compat//:compat.bzl (in workspace), CONTAINING_PACKAGE_LOOKUP:@io_bazel_rules_go_compat//, PACKAGE_LOOKUP:@io_bazel_rules_go_compat//, REPOSITORY:@io_bazel_rules_go_compat, REPOSITORY_DIRECTORY:@io_bazel_rules_go_compat]], isCatastrophic=false, rootCauseOfException=null, isDirectlyTransient=false, isTransitivelyTransient=false}

My `WORKSPACE` file looks like this:
```
http_archive(
    name = "io_kythe",
    sha256 = "9203fdffa3294f5f36b2732650e1dd3e0e289d702c4b4cae1cd04d53e14c0397",
    strip_prefix = "kythe-85460a0286a2de821dc46cdbac3124d9573b0750",
    urls = [
        # Release v0.0.36.
        "https://github.com/kythe/kythe/archive/85460a0286a2de821dc46cdbac3124d9573b0750.tar.gz"
    ],
)

load("@io_kythe//:setup.bzl", "kythe_rule_repositories")

kythe_rule_repositories()

load("@io_kythe//:external.bzl", "kythe_dependencies")

kythe_dependencies()
```

I used a `WORKSPACE` from:
https://github.com/kythe/kythe/blob/85460a0286a2de821dc46cdbac3124d9573b0750/kythe/examples/bazel/bazel.WORKSPACE#L1-L16

**Comment by ipetr0v** [comment]
Could it be the same problem as in https://github.com/bazelbuild/rules_go/issues/1937 ?

**Comment by ipetr0v** [comment]
Also, if I will change `WORKSPACE` like this (remove `kythe_rule_repositories`):
```
http_archive(
    name = "io_kythe",
    sha256 = "9203fdffa3294f5f36b2732650e1dd3e0e289d702c4b4cae1cd04d53e14c0397",
    strip_prefix = "kythe-85460a0286a2de821dc46cdbac3124d9573b0750",
    urls = [
        # Release v0.0.36.
        "https://github.com/kythe/kythe/archive/85460a0286a2de821dc46cdbac3124d9573b0750.tar.gz"
    ],
)

load("@io_kythe//:external.bzl", "kythe_dependencies")

kythe_dependencies()
```

I get the following error:
/opt/my-project# bazel sync
ERROR: ErrorInfo{exception=null, rootCauses={}, cycles=[[] -> [[/opt/my-project]/[WORKSPACE], 8, @io_kythe//:external.bzl (in workspace), @bazel_gazelle//:deps.bzl (in workspace), CONTAINING_PACKAGE_LOOKUP:@bazel_gazelle//, PACKAGE_LOOKUP:@bazel_gazelle//, REPOSITORY:@bazel_gazelle, REPOSITORY_DIRECTORY:@bazel_gazelle]], isCatastrophic=false, rootCauseOfException=null, isDirectlyTransient=false, isTransitivelyTransient=false}

**Comment by shahms** [comment]
If you're attempting to depend on the Kythe source as an external repository, there are a good number more dependencies than just those from `setup.bzl` and `external.bzl`. In particular: https://github.com/kythe/kythe/blob/master/WORKSPACE#L28

**Comment by shahms** [comment]
The Kythe releases are substantially different than the Kythe source.
