### ISSUE TITLE
Non-existing directory in the compilation database

### ISSUE THREAD

**Issue by ipetr0v** [kythe/kythe#4238]
I'm trying to use Kythe in order to generate compilation database JSON file from Bazel, so I could use `clang-tidy`.

I'm building target with the following option:
```bash
bazel build --experimental_action_listener=@io_kythe//kythe/cxx/tools/generate_compile_commands:extract_json //:hello-world
```
Then I run the following:
https://github.com/kythe/kythe/blob/77e1360beca7903bc97728097d2c5e1b82204092/tools/cpp/generate_compilation_database.sh#L14-L19

I'm tying to analyze file with:
```bash
clang-tidy -p "$(bazel info execution_root)" hello-world.cc
```
taken from:
https://github.com/kythe/kythe/blob/77e1360beca7903bc97728097d2c5e1b82204092/tools/clang_tidy/clang_tidy.sh#L11
but get the following error:
```
Skipping /opt/test/hello-world.cc. Compile command not found.
```

The `compile_commands.json` file generated by Kythe looks as follows:
```json
[{
"file":"hello-world.cc",
"directory":"/root/.cache/bazel/_bazel_root/87dce07284a1eb76b6a67b97c6a39dcd/sandbox/processwrapper-sandbox/232/execroot/test",
"command":"..."
}]
```
It seems that this file points to a `.../processwrapper-sandbox/$PID/` directory that doesn't exist after Bazel finished compiling.

**Comment by ipetr0v** [comment]
Should the `directory` be equal to `$(bazel info execution_root)` ?
Because, when I'm manually changing it, `clang-tidy` starts working.

**Comment by shahms** [comment]
It looks like Bazel changed the name of the sandbox directory: https://github.com/kythe/kythe/blob/master/kythe/cxx/tools/generate_compile_commands/extract_compile_command.cc#L76

**Comment by ipetr0v** [comment]
After `bazel build` `hello-world.cc` is in the following directory:
```bash
/opt/test# echo $(bazel info execution_root)
/root/.cache/bazel/_bazel_root/87dce07284a1eb76b6a67b97c6a39dcd/execroot/test
```
```bash
/opt/test# ls $(bazel info execution_root)
BUILD  WORKSPACE  bazel-out  compile_commands.json  external  hello-world.cc
```

**Comment by ipetr0v** [comment]
And sandbox directories are empty:
```bash
/opt/test# ls /root/.cache/bazel/_bazel_root/87dce07284a1eb76b6a67b97c6a39dcd/sandbox/processwrapper-sandbox/ -la
total 8
drwxr-xr-x 2 root root 4096 Dec  3 16:29 .
drwxr-xr-x 3 root root 4096 Dec  3 16:27 ..
```

**Comment by shahms** [comment]
Ultimately that entire script is a big hack and most of the logic should probably be moved into the clang_tidy.sh wrapper to avoid having to compile the entire project just to get the command line flags for a single file. It's always been pretty fragile and unsupported (I don't think anyone on the Kythe team actually uses it for anything these days).
