### ISSUE TITLE
Schema for "file" node has empty language

### ISSUE THREAD

**Issue by kamahen** [kythe/kythe#4246]
Why is the "language" entry empty for node [file](https://kythe.io/docs/schema/#file)?

If a source code browser wants to colorize a file, then it would want to know the language. Of course, it can use a convention from the file name (e.g., ".java", ".py", ".js"); but wouldn't it be better to use the information from the indexer? If the file type isn't known (e.g., it's a data file in the source tree), it could still be left empty.

[Another possibility is for the indexer to output colorization information, such as "keyword", "comment", "name"]

**Comment by shahms** [comment]
There are a variety of reasons for this, among them are the fact that file nodes serve as something of a "gateway" into the graph and having to know language to "spell" that name is a further barrier.  Another is that files often lack a single language by which they can be known.  A single header file, for example, could conceivably be indexed as any or all of C, C++, Objective-C, SWIG, etc. and would likely have different decorations and cross references for each.  Or a Python file being indexed as both Python 2 and Python 3, which could yield different decorations but should still be known as the same "file".

**Comment by creachadair** [comment]
As @shahms says, the main issue is that we want to be able to utter the identity of a file without the need to know what language(s) it contains. Language is a _property_ of the file, rather than part of its identity.

**Comment by kamahen** [comment]
So, `language` is part of the signature for an anchor because you might want to say "when I interpret this file as a C++ program, then it's an anchor" but if I interpret it as an m4 program (which generates C++), then I might want to interpret it differently? This seems to be an extreme corner case, and I'm not even sure it makes sense ... so I'm guessing that there's another reason for `language` being part of the signatures?

Anyway, I hope you agree with https://github.com/kythe/kythe/pull/4252, which allows an optional `F.language "java"` (it doesn't allow multiple languages for a single file).

**Comment by creachadair** [comment]
> So, `language` is part of the signature for an anchor because you might want to say "when I interpret this file as a C++ program, then it's an anchor" but if I interpret it as an m4 program (which generates C++), then I might want to interpret it differently?

Broadly yes. The `language` in the VName means that indexer A doesn't have to worry about whether the rules it uses to generate signatures might be similar to what indexer B uses. Without that field, either A would have to know what B does (and C and D) so as to avoid it, or inject some special prefix (such as a language label) to ensure distinct namespaces.
