### ISSUE TITLE
http_server can produce invalid proto JSON

### ISSUE THREAD

**Issue by isker** [kythe/kythe#4288]
1. When analyzing Java code, `KytheTreeScanner` can emit a fact mapped to an empty string: https://github.com/kythe/kythe/blob/33bbb90c2284676d6c5acc76f76fe3e41a22c445/kythe/java/com/google/devtools/kythe/analyzers/java/KytheTreeScanner.java#L655-L657

2. http_server returns proto JSON with a null map value for such a fact.  (This presumably is because the empty string is the nil string value in go.)
```
$ kythe -json -api http://localhost:8080 nodes -filters '/kythe/tag/static' kythe://kythe?lang=java?path=com.foo.ClassWithAStaticField.java#someFieldLabel
{"kythe://kythe?lang=java?path=com.foo.ClassWithAStaticField.java#someFieldLabel":{"facts":{"/kythe/tag/static":null}}}
```
3. When deserializing such JSON, the Java protobuf library rejects this as an invalid encoding.
```
 com.google.protobuf.InvalidProtocolBufferException: Map value cannot be null.
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeMapField(JsonFormat.java:1693)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeField(JsonFormat.java:1659)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1502)
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1460)
	at com.google.protobuf.util.JsonFormat$ParserImpl.parseFieldValue(JsonFormat.java:2001)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeMapField(JsonFormat.java:1688)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeField(JsonFormat.java:1659)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1502)
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1460)
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1342)
	at com.google.protobuf.util.JsonFormat$Parser.merge(JsonFormat.java:477)
```
See https://github.com/protocolbuffers/protobuf/blob/v3.11.1/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1689-L1695 for the code.

It sounds like a bug or limitation in the [go JSON encoder](https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go), to me.  But I have low familiarity with Kythe, protobufs, and go, so I figure I'd ask here to start.

I was able to work around this in my Java client by passing `?proto=true` to activate the [undocumented binary encoding switch](https://github.com/kythe/kythe/blob/b10bcff3bcdbceaa143c02013b7de4a6147d2f91/kythe/go/services/web/web.go#L87-L94) in http_server and decoding it as such in the client.  That encoding does not have this problem.

**Comment by shahms** [comment]
This seems like a bug in either the Java proto json unmarshalling or the Go proto marshalling code, but I don't know which.

**Comment by isker** [comment]
It's at least intended that the Java unmarshaller rejects this https://github.com/protocolbuffers/protobuf/issues/5113.

**Comment by shahms** [comment]
The `jsonpb` encoder distinguishes between "" and `nil` values in bytes-valued maps, which it likely should not, e.g.
```
message ByteMap {
  map<string, bytes> mapping = 1;
}

jsonpb.Marshal(ByteMap{Mapping: map[string][]byte{
  "nil": nil,
  "empty": []byte{},
}}) => {"mapping": {"nil": null, "empty": ""}}
```

**Comment by shahms** [comment]
https://github.com/golang/protobuf/issues/1006

**Comment by isker** [comment]
Thanks for figuring that out.

**Comment by shahms** [comment]
Sure.  While we could work around this in code, given that the idiomatic "empty slice" is spelled `nil`, this feels like something which should be fixed upstream as it's *very* likely to regress at some point if not.

**Comment by isker** [comment]
I suppose https://blog.golang.org/a-new-go-api-for-protocol-buffers heralds the availability of a fix to this problem.  But it needs an upgrade in Kythe.

**Comment by shahms** [comment]
Yeah, given the resolution of the upstream bug report I would hope it was fixed in the new API :-)

**Comment by shahms** [comment]
Migrating to the new API is currently somewhat blocked behind https://github.com/bazelbuild/rules_go/issues/2395

**Comment by schroederc** [comment]
#4529 fixes this

```
$ kythe --json nodes kythe://kythe?lang=java?path=com.google.devtools.kythe.analyzers.java.KytheTreeScanner#757bcdfcc7195b5a44b1d5f9ccddae293e12f2d5b18572505f6c2fa913385bed
{"kythe://kythe?lang=java?path=com.google.devtools.kythe.analyzers.java.KytheTreeScanner#757bcdfcc7195b5a44b1d5f9ccddae293e12f2d5b18572505f6c2fa913385bed":{"facts":{"/kythe/node/kind":"dmFyaWFibGU=","/kythe/subkind":"ZmllbGQ=","/kythe/tag/static":""}}}
```
