### ISSUE TITLE
runextractor produces no files when building Maven project

### ISSUE THREAD

**Issue by BFergerson** [kythe/kythe#4374]
I'm following instructions at https://github.com/kythe/kythe/tree/master/kythe/go/extractors/config/runextractor and having issues producing .kindex or .kzip files. I'm using Kythe v0.0.41.

Running the following commands:
```sh
git clone https://github.com/bfergerson/otherproject
cd otherproject

export REAL_JAVAC="$(which javac)"
export KYTHE_CORPUS="github.com/bfergerson/otherproject"
export KYTHE_OUTPUT_DIRECTORY="/tmp/kythe"
export KYTHE_OUTPUT_FILE="/tmp/kythe/done.kzip"
export KYTHE_ROOT_DIRECTORY="$PWD"
export JAVAC_EXTRACTOR_JAR="/opt/kythe/extractors/javac_extractor.jar"
export KYTHE_JAVA_RUNTIME_OPTIONS="-Xbootclasspath/p:/opt/kythe-v0.0.41/jsr250-api-1.0.jar"

mkdir -p "$KYTHE_OUTPUT_DIRECTORY"
/opt/kythe/tools/runextractor maven -javac_wrapper /opt/kythe/extractors/javac-wrapper.sh
```

Results in no output. It would seem everything worked but the `KYTHE_OUTPUT_FILE` file is not produced. I found out that running:
```sh
mvn clean install \
-Dmaven.compiler.forceJavacCompilerUse=true \
-Dmaven.compiler.fork=true \
-Dmaven.compiler.executable=/opt/kythe/extractors/javac-wrapper.sh
```

Results in:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.647 s
[INFO] Finished at: 2020-02-15T08:19:46-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project other-project: Compilation failure -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

And I can fix that by running:
```sh
mvn clean install \
-Dmaven.compiler.forceJavacCompilerUse=true \
-Dmaven.compiler.fork=true \
-Dmaven.compiler.executable=/opt/kythe/extractors/javac-wrapper.sh \
-Dmaven.compiler.source=1.8 \
-Dmaven.compiler.target=1.8
```

However, still no `KYTHE_OUTPUT_FILE` file is created.

I also found that adding:
```xml
<properties>
 <maven.compiler.source>1.8</maven.compiler.source>
 <maven.compiler.target>1.8</maven.compiler.target>
</properties>
```

To the `pom.xml` file also fixes the build error, but still no `KYTHE_OUTPUT_FILE` file is created.

---

So I have some questions:
 - Why is there no `KYTHE_OUTPUT_FILE` file created even when Maven ends with a successful build?
 - How can I pass Maven settings to runextractor so I don't have to modify the pom.xml file?
 - What should the value of `KYTHE_JAVA_RUNTIME_OPTIONS` be?
   - Searching this repo suggests it should be `javac9_tools.jar` but I don't have that file in my Kythe installation.

**Comment by shahms** [comment]
Justin, Daniel could one of you take a look at this? I think you have the most experience with Graden and Mavle?

**Comment by justbuchanan** [comment]
I spent some time on this and it looks like you're hitting a similar issue as in #4392:

```
ERROR: Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/javac/main/Option
ERROR: 	at java.lang.Class.getDeclaredMethods0(Native Method)
ERROR: 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2703)
ERROR: 	at java.lang.Class.privateGetMethodRecursive(Class.java:3050)
ERROR: 	at java.lang.Class.getMethod0(Class.java:3020)
ERROR: 	at java.lang.Class.getMethod(Class.java:1786)
ERROR: 	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:540)
ERROR: 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:522)
ERROR: Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.main.Option
ERROR: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
ERROR: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
ERROR: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:350)
ERROR: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
ERROR: 	... 7 more
```

Unfortunately it's very difficult to get the actual error messages out of maven. It parses the output of the compiler and only forwards warnings and errors with a specific format to its output, so it ends up dropping messages that come out of `javac-wrapper.sh`. I tried `-e`, `-X`, `--debug` and none of them kept the extractor's output from being dropped. I ended up modifiying `javac-wrapper.sh` to log its output to a file so I could actually read it.

I sent https://github.com/kythe/kythe/pull/4397 to improve the output of `runextractor` a bit, but it doesn't stop maven from dropping the extractor's stderr. If you have any ideas on how to fix that, let me know.

**Comment by BFergerson** [comment]
Confirmed downloading `javac-9+181-r4173-1.jar` and setting `KYTHE_JAVA_RUNTIME_OPTIONS` to that jar file fixed my issue here. Thanks for looking into this.
