### ISSUE TITLE
include class ctors in references for the class itself

### ISSUE THREAD

**Issue by shahms** [kythe/kythe#4381]
When looking at references and definitions of a class, Kythe currently returns:
```
struct [[Foo]] {
   Foo();
   Foo(const [[Foo]]&);
   ~[[Foo]]();
};
```
This is suboptimal if one is looking to rename a class, for example.  Following the example with the destructor, the constructor should have a ref to the class name which overlaps the defines/binding edge for the ctor.  I believe these were inhibited prior due to poor UI/client support for overlapping ranges, but this handling is much better now.

**Comment by zrlk** [comment]
Could you write the proposal out as a verifier script?

I believe we already have the information in the graph. Functions that are constructors or destructors of a class should be childof that class and have subkind constructor (or destructor).

**Comment by shahms** [comment]
Yes, I think we actually have to suppress these currently.

```
//- @Foo defines/binding FooStruct
struct Foo {
  //- @Foo defines/binding FooCtor
  //- @Foo ref FooStruct
  Foo();
  //- @#0Foo defines/binding FooCopyCtor
  //- @#0Foo ref FooStruct
  //- @#1Foo ref FooStruct
  Foo(const Foo&);
  //- @"~Foo" defines/binding FooDtor
  //- @Foo ref FooStruct
  ~Foo(); 
};
```

Right now, Kythe only emits `ref FooStruct` for the parameters and the destructor, not the constructors.

**Comment by shahms** [comment]
Yes, the information is in the graph, but not included in the list of references to a particular class.

**Comment by shahms** [comment]
It *looks* like this should already Just Work, but Clang is failing to fill out the requisite TypeSourceInfo for class constructors, only destructors.

**Comment by zrlk** [comment]
I'm still not completely convinced that the `Foo` in the constructor `Foo()` should be a reference to the class `Foo` (in the same way that a member function with `Foo` as a return type would ref the class `Foo`).

**Comment by jaysachs** [comment]
I think if you squint and treat it as sugar for combined name/return type, it can make sense.

**Comment by shahms** [comment]
It's the current (and historical) behavior for destructors.  It appears to not be the case for constructors due to a bug in Clang.

**Comment by creachadair** [comment]
> I think if you squint and treat it as sugar for combined name/return type, it can make sense.

It _can_ make sense, but it's still weird. The object construction protocol consists of allocation and initialization, and the code the user writes is just a method with special syntax to affect the second part. (I don't know if JVM has a hook to override allocation, but I wouldn't be surprised). The fact that the grammar requires it to have the same name as the class is, arguably, a distraction—we wouldn't call the `__init__` method in a Python class a reference to the class, right?

**Comment by shahms** [comment]
No, but Python also doesn't use the class name itself to signify the constructor/destructor.  This specifically came from a request from someone trying to automate finding the places which need to change when one is renaming a class, which is both common and for which one would expect to find the constructor and destructor.  From both the language and user perspectives, they *are* references to the class.

Regardless, we should be consistent here and either add a reference from the ctor (my preference) or remove the reference from the dtor (easier, apparently).

**Comment by shahms** [comment]
After some discussion with clang folks, it sounds like this is a bug in clang although no idea if/when it might be fixed.  It seems pretty straightforward to fix in Clang, but my naive approach broke a few things.

**Comment by shahms** [comment]
While I've committed this change for now, we'd like to discuss whether or not this is the right approach and apply it uniformly.  This would mean either providing the same behavior in Java or suppressing the decoration on the destructor in C++.
