### ISSUE TITLE
runextractor looking for gradle.build instead of build.gradle

### ISSUE THREAD

**Issue by BFergerson** [kythe/kythe#4392]
Using Kythe v0.0.42 and running the following commands:

```sh
git clone https://github.com/bfergerson/otherproject-gradle
cd otherproject-gradle

export REAL_JAVAC="$(which javac)"
export KYTHE_CORPUS="github.com/bfergerson/otherproject-gradle"
export KYTHE_OUTPUT_DIRECTORY="/tmp/kythe"
export KYTHE_OUTPUT_FILE="/tmp/kythe/done.kzip"
export KYTHE_ROOT_DIRECTORY="$PWD"
export JAVAC_EXTRACTOR_JAR="/opt/kythe/extractors/javac_extractor.jar"
export KYTHE_JAVA_RUNTIME_OPTIONS="-Xbootclasspath/p:/usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar"

mkdir -p "$KYTHE_OUTPUT_DIRECTORY"
/opt/kythe/tools/runextractor gradle -javac_wrapper /opt/kythe/extractors/javac-wrapper.sh
```

Results in:
```
2020/02/24 04:46:32 error backing up gradle.build: open gradle.build: no such file or directory
```

This seems erroneous considering `gradle.build` isn't what Gradle recommends to name the build file but rather `build.gradle` (https://guides.gradle.org/creating-new-gradle-builds/).

If I change the runextractor command to:
```sh
/opt/kythe/tools/runextractor gradle -javac_wrapper /opt/kythe/extractors/javac-wrapper.sh -build_file build.gradle
```

The command works, but with no output. I then run `gradle clean build`, which results in:
```
EXTRACT ERR: Feb 24, 2020 5:08:06 AM com.google.devtools.kythe.extractors.java.JavaCompilationUnitExtractor findModuleClassLoader
EXTRACT ERR: INFO: Running on non-modular JDK, fallback compiler unavailable.
EXTRACT ERR: Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/javac/main/Arguments
EXTRACT ERR:    at com.google.devtools.kythe.extractors.java.standalone.Javac8Wrapper.processCompilation(Javac8Wrapper.java:49)
EXTRACT ERR:    at com.google.devtools.kythe.extractors.java.standalone.AbstractJavacWrapper.process(AbstractJavacWrapper.java:94)
EXTRACT ERR:    at com.google.devtools.kythe.extractors.java.standalone.Javac8Wrapper.main(Javac8Wrapper.java:127)
EXTRACT ERR: Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.main.Arguments
EXTRACT ERR:    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
EXTRACT ERR:    at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
EXTRACT ERR:    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
EXTRACT ERR:    at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
EXTRACT ERR:    ... 3 more
warning: [options] bootstrap class path not set in conjunction with -source 8
1 warning
```

This seems to suggest something wrong with my JDK but my current version is JDK8:
```sh
$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

I removed the following lines from the `build.gradle` file:
```
allprojects {
  gradle.projectsEvaluated {
    tasks.withType(JavaCompile) {
      options.fork = true
      options.forkOptions.executable = '/opt/kythe/extractors/javac-wrapper.sh'
    }
  }
}
```

I'm then able to build successfully so I know there isn't a problem with my project.

I'm also having trouble running Maven with runextractor (see #4374). I would really appreciate help on that issue even if it's just instructions on how to increase logging to debug the issue further myself.

**Comment by shahms** [comment]
Justin, Daniel could one of you take a look at this? I think you have the most experience with Gradle and Maven?

**Comment by shahms** [comment]
The error suggests that the extractor can't find `com.sun.tools.javac.main.Arguments` which should come from the embedded langtools jar when running on JDK8, but appears not to be found and could very well be related to the missing bootclaspath warning.

**Comment by shahms** [comment]
If you can, I would try to migrate to JDK9+.  Support for running the extractor on JDK8 is unlikely to survive the year.

**Comment by justbuchanan** [comment]
Thanks for the detailed report.

I fixed the default of `runextractor --build_file` in https://github.com/kythe/kythe/pull/4393.

The NoClassDefFoundError is a bit trickier, but there are a couple options to get it working. The kythe project contains a copy of r4173.jar, which includes the missing classes. Adding it to your bootclasspath should get things working. Try `# export KYTHE_JAVA_RUNTIME_OPTIONS=-Xbootclasspath/p:/path/to/kythe/third_party/javac/javac-9+181-r4173-1.jar`

The other option, as shahms mentioned, is to use JDK9+. On my system, I got it working using javac 11. I also had to update to a newer gradle by changing this line in gradle-wrapper.properties: `distributionUrl=https\://services.gradle.org/distributions/gradle-6.0.1-all.zip`.

**Comment by BFergerson** [comment]
@justbuchanan, I'll try out your recommendations soon, thanks. As for `KYTHE_JAVA_RUNTIME_OPTIONS`, I thought `javac-9+181-r4173-1.jar` was the correct value but this file isn't included in the Kythe distribution so I wasn't sure. Shouldn't that file be included in the distribution because currently it doesn't seem to be:
```sh
wget -O kythe-v0.0.42.tar.gz https://github.com/kythe/kythe/releases/download/v0.0.42/kythe-v0.0.42.tar.gz
tar -xvzf kythe-v0.0.42.tar.gz
cd kythe-v0.0.42
locate javac-9+181-r4173-1.jar
```

The locate command finds nothing.

**Comment by justbuchanan** [comment]
You're right that we should probably include that in the distribution. It wouldn't be hard to add that jar to our release archive, but I was hoping to be able to bundle it as part of `javac_extractor.jar` and avoid having to pass command line flags to get it working. So far I haven't had luck getting that to work though: https://github.com/kythe/kythe/pull/4395.

**Comment by BFergerson** [comment]
Confirmed downloading `javac-9+181-r4173-1.jar` and setting `KYTHE_JAVA_RUNTIME_OPTIONS` to that jar file fixed my issue here. Thanks for looking into this.
