### ISSUE TITLE
bazel-extractor docker image should support c++17

### ISSUE THREAD

**Issue by justbuchanan** [kythe/kythe#4401]
Our docker image is failing to extract the kythe repo since we [switched to c++17](https://github.com/kythe/kythe/commit/509d7c618a5203682566fbcf5fc0572a87dddef2).

The relevant packages we have in the image are: `libstdc++-5-dev` and `clang-6.0`.

Our docker image is based on the official bazel image: https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/bazel/Dockerfile, which uses ubuntu 16.04.

We may need a ppa to get a newer version of the c++ stdlib.

**Comment by shahms** [comment]
We should just be able to base in on 18.04 instead (which supports C++17 and is what I had to do to get our RBE image to do so).

**Comment by justbuchanan** [comment]
Sounds good to me. I don't think we get a whole lot from extending the bazel image - I can copy the bits we need into our dockerfile.
