### ISSUE TITLE
bazel hangs on macos

### ISSUE THREAD

**Issue by mellery451** [kythe/kythe#4408]
I'm a bazel newb...apologies if I've missed something obvious. 

I did a clean checkout on macos. bazel and other prerequisites are installed via homebrew. bazel version is 2.1.1.

*any* bazel command from the root of this checkout hangs indefinitely. bazel commands outside of this repo work just fine. I've also successfully built a few other repos (abseil e.g.) on this machine with no issues.

any idea how to diagnose further? I get no output from bazel at all, so it's tough to tell what's going on.

**Comment by justbuchanan** [comment]
I don't have any good suggestions at the moment, but one thing you could try is to look at the logs after running bazel (and cancelling it after a bit). Logs should be at `$(bazel info output_base)/java.log`. Hopefully the `bazel info` command doesn't get stuck too.

What version of mac os do you have?

**Comment by mellery451** [comment]
`bazel info` *does* hang...as well as `bazel version`, `bazel help`, etc. Outside of the directory, they run fine (well, `bazel info` fails outside of a workspace..). I don't think any files are being produced at all (no logs, etc.). I'm stumped, but I'll probably start commenting out sections of `WORKSPACE` to see if I can get it to unstick.

**Comment by creachadair** [comment]
I tried to reproduce this, and noticed that following the instructions on https://kythe.io/getting-started-macos/ will only get you Bazel 2.1.0 not 2.1.1. It looks like maybe a stock `brew install bazel` will actually work now (it did not the last time I updated those instructions). Is that what you did to get your Bazel installation?

With 2.1.0 (and a locally patched `.bazelversion` file) I am not seeing this error FWIW.

**Comment by creachadair** [comment]
I uninstalled Bazel 2.1.0 from bazelbuild/tap, and installed the "stock" 2.1.1. I had to do some extra shenanigans to update my JDK installation (I guess the dependencies are wired up differently). Now that I've done this, I can reproduce the symptoms described above: Specifically, it doesn't seem to hang, but spins in a loop calling a sequence of commands.

The processes come and go too quickly for me to see what's going on, but it looks like it sets `JAVA_HOME` by calling `/usr/libexec/java_home --version 1.8` and then runs some hairy Bash script to figure out where the real binary is. If I just run that binary directly (which on my system is `/usr/local/Cellar/bazel/2.1.1/libexec/bin/bazel-real`) it seems to work: You can build and query and everything is fine.

So I am guessing something is borked with that script, but I didn't have the patience to decode it all.

**Comment by creachadair** [comment]
Ok, so with the Homebrew install of Bazel, we have

- `which bazel` is `/usr/local/bin/bazel`
- which is a symlink to `/usr/local/Cellar/bazel/2.1.1/bin/bazel`
- which is a shell script that sets `JAVA_HOME` and runs `/usr/local/Cellar/bazel/2.1.1/libexec/bin/bazel`
- which is a shell script that (after some path shenanigans) runs `exec -a /usr/local/Cellar/bazel/2.1.1/libexec/bin/bazel /usr/local/Cellar/bazel/2.1.1/libexec/bin/bazel-2.1.1 version`

Which, as you may observe, is the same script.

I think this is probably a bug in the Bazel script, or maybe in the way that the Homebrew formula sets it up. I added `set -x` to the top of that script and watched it run for a while, and it does figure out that the "real" path is `readonly bazel_real_path=/usr/local/Cellar/bazel/2.1.1/libexec/bin/bazel-real`, but for whatever reason doesn't use that.

**Comment by creachadair** [comment]
I found a workaround that seems to help:

```
ln -s /usr/local/Cellar/bazel/2.1.1/libexec/bin/bazel-real tools/bazel
```

The default script looks for `tools/bazel` in the current workspace, and if it finds that "assumes you know what you're doing" and runs it in place of whatever other nonsense it is promulgating.

**Comment by creachadair** [comment]
Alternative workaround:

```shell
brew uninstall bazel
brew tap bazelbuild/tap
brew install bazelbuild/tap/bazel
echo "2.1.0" > .bazelversion  # in $KYTHE_DIR
```

The last line is needed because for some reason the bazelbuild/tap version is a release behind. But that version works without the extra Java package. At some point that will probably stop working and I'll need to update the setup instructions again.

**Comment by mellery451** [comment]
Thanks for doing all that investigation! The `ln` workaround above is working for me, and I'm sure the tap install would work as well. I appreciate the insight.

**Comment by mellery451** [comment]
FWIW - it seems like  `bazelisk` is another option (intalled via homebrew)...then I'm able to do something like `USE_BAZEL_VERSION=2.1.1 bazelisk build //...`

**Comment by shahms** [comment]
Bazelisk should work.  Seeing as we get new versions of bazel pushed to our workstations pretty eagerly, we tend to keep `.bazelversion` in the repository pretty up-to-date.
