### ISSUE TITLE
unpacking a release fails (ubuntu 18.04)

### ISSUE THREAD

**Issue by mellery451** [kythe/kythe#4430]
I've followed the instructions to create a release build at: https://kythe.io/getting-started/#build-a-release-of-kythe-using-bazel-and-unpack-it-in-optkythe  . Once I get to the unpack step, I fail:

```
...
./kythe-v0.0.42/tools/read_entries
./kythe-v0.0.42/tools/kzip_validator
tar: .: Cannot utime: Operation not permitted
tar: .: Cannot change mode to rwxr-xr-x: Operation not permitted
tar: Exiting with failure status due to previous errors
```

The location I unpack to doesn't seem to matter (I've tried `/opt`, `/tmp`, etc.) FWIW, I get the same error with the official release tarballs (which I was trying a local build in the first place).

**Comment by shahms** [comment]
Can you untar anything else in those same locations?  If tar can't chmod a file, that seems like a bigger problem than would be caused by our specific tar balls.

**Comment by mellery451** [comment]
yes - most of this archive has already extracted when this error occurs. `./tools/kzip_validator` seems to be last file written (see my truncated output above).

**Comment by shahms** [comment]
It looks like tar is failing to modify the current working directory (`.`) which is odd.

**Comment by shahms** [comment]
```
$ tar --list -f bazel-bin/kythe/release/kythe-v0.0.42.tar.gz
./
./kythe-v0.0.42/
....
```

The archive should not include that first entry :-(
