### ISSUE TITLE
Struggling to build a Kythe index under Docker

### ISSUE THREAD

**Issue by iphydf** [kythe/kythe#4504]
* I gave up on trying to build Kythe on Docker, because I either run into https://github.com/golang/go/issues/37436 or end up not being able to compile Kythe's C++ code because the stdlib is too old (e.g. no `<string_view>`).
* I can't run the extractors on anything lower than ubuntu 20.04, because they need a super recent glibc. This is sort of fine, I can run ubuntu 20.04.
* I can't run write_tables at all, because of the golang runtime issue.
* Upgrading my kernel is not an option at this time.
* I can't seem to be able to get `--ulimit` to work for `docker build`.
* I *can* run `docker --privileged`, but I won't be able to do that on the CI docker builds.

Has anyone got indexing to work under Docker? Running it outside Docker isn't really an option for me long term.

**Comment by shahms** [comment]
Ubuntu 18.04 should work (as we need C++17) and is what our various CI infrastructure runs on.

**Comment by iphydf** [comment]
This dockerfile fails because of the mlock issue:
```Dockerfile
FROM ubuntu:18.04

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
 asciidoc \
 bison \
 build-essential \
 default-jdk \
 flex \
 git \
 graphviz \
 source-highlight \
 unzip \
 wget \
 zip \
 zlib1g-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel_3.1.0-linux-x86_64.deb \
 && dpkg -i bazel_3.1.0-linux-x86_64.deb \
 && rm bazel_3.1.0-linux-x86_64.deb

ENV CC=gcc CXX=g++

WORKDIR /src/kythe
RUN git clone --depth=1 https://github.com/kythe/kythe /src/kythe
RUN bazel build //kythe/release
```

It fails on Linux 5.2. It works on Travis (apparently a recent enough kernel there). I think the issue said that it would work with golang 1.13, but broke in 1.14. Is there a way to force 1.13?

**Comment by iphydf** [comment]
`docker --ulimit memlock=67108864` works. I think this is acceptable, as on CI I generally control the docker invocation.

**Comment by iphydf** [comment]
By the way, I'm trying to get the webui up and running with my code. If there is some documentation I could follow to set that up, I haven't found it and would be grateful for pointers. In the meantime, I'm looking around the various scripts in the repo for hints on how to deploy it.

**Comment by shahms** [comment]
The in-tree UI is unsupported and largely unmaintained (and we really should delete it at some point).  You may have better luck getting Underhood working: https://groups.google.com/g/kythe/c/9XzG5e0JyeQ/m/BRLGTfm-CwAJ

**Comment by iphydf** [comment]
I got it working, and I'm very happy with it: http://csrch.herokuapp.com/#c-toxcore/toxcore/Messenger.c?corpus=toktok&signature

Now on to look at Underhood. Thanks for that pointer, I hadn't heard of that.

**Comment by iphydf** [comment]
In case anyone stumbles across this issue and wants to replicate this with their codebase, all the dockerfiles for kythe builds are here: https://github.com/TokTok/dockerfiles/tree/master/kythe
