### ISSUE TITLE
external/org_llvm/include/llvm/ADT/StringRef.h:22:10: fatal error: 'string_view' file not found

### ISSUE THREAD

**Issue by aashish29n** [kythe/kythe#4527]
Hi,

I am new to kythe and i got stuck due to some error while building Kythe from source code.

These are the steps that i performed:-

1)  I cloned the Kythe directory using git clone https://github.com/kythe/kythe.git
2)  Added kythe directory path to my bashrc file.
3)  Installed all the external dependencies and installed Debian Jessie Packages

echo deb http://http.debian.net/debian jessie-backports main >> /etc/apt/sources.list
apt-get update

apt-get install \
    asciidoc asciidoctor source-highlight graphviz \
    gcc uuid-dev libncurses-dev flex clang-8 bison \
    openjdk-8-jdk \
    parallel \
    wget
 
4) Then i set my CC variable to clang path in bazelrc(3.1.0).
    echo 'build --client_env=CC=/usr/bin/clang-8' >>~/.bazelrc

5) Then i tried to build Kythe source code using bazel.

    bazel build //...

But while performing this step i am getting this error:-

   ERROR: /build/locadmin/.cache/bazel/_bazel_root/3c3553b5169933bb2d3ad18fa8d54dcd/external/org_llvm/BUILD.bazel:208:1: C++ compilation of rule '@org_llvm//:clang-tblgen' failed (Exit 1) clang failed: error executing command /usr/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 38 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/org_llvm/tools/clang/utils/TableGen/ClangOpcodesEmitter.cpp:14:
In file included from external/org_llvm/include/llvm/TableGen/Error.h:17:
In file included from external/org_llvm/include/llvm/Support/SourceMgr.h:19:
In file included from external/org_llvm/include/llvm/Support/MemoryBuffer.h:18:
external/org_llvm/include/llvm/ADT/StringRef.h:22:10: fatal error: 'string_view' file not found
#include <string_view>
         ^~~~~~~~~~~~~
1 error generated.
INFO: Elapsed time: 22.204s, Critical Path: 18.77s
INFO: 649 processes: 640 processwrapper-sandbox, 9 worker.
FAILED: Build did NOT complete successfully

i am using Ubuntu 16.04.5

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

Need Help!!!

Thanks,
Aashish

**Comment by justbuchanan** [comment]
One suggestion to help debug would be to pass `-s` when building, which will print out more detailed info on what compiler is being used, header search paths, etc. Something like `bazel build -s //...`.

Also, you may need to specify `CXX` in addition to `CC` in your .bazelrc: `build --client_env=CXX=/usr/bin/clang++-8'`.

**Comment by aashish29n** [comment]
Hi Justbuchanan,
Thanks for the follow up. 

I tried building Kythe with **bazel build -s //...** after adding CXX variable to my .bazelrc as you suggested. But i got the same error msg with some additional information .

Here's the error msg:-

SUBCOMMAND: # //kythe/java/com/google/devtools/kythe/extractors/java/standalone:javac9_extractor [action 'Building deploy jar kythe/java/com/google/devtools/kythe/extractors/java/standalone/javac9_extractor_deploy.jar', configuration: c5096c03bbd0a60e1f582b3b43e8b5979e947ee6822cd91c6190d9c1de707d57]
(cd /build/locadmin/.cache/bazel/_bazel_root/3c3553b5169933bb2d3ad18fa8d54dcd/execroot/io_kythe && \
  exec env - \
  external/remote_java_tools_linux/java_tools/src/tools/singlejar/singlejar_local @bazel-out/k8-fastbuild/bin/kythe/java/com/google/devtools/kythe/extractors/java/standalone/javac9_extractor_deploy.jar-0.params)
SUBCOMMAND: # @org_llvm//:LLVMDebugInfoCodeView [action 'Compiling external/org_llvm/lib/DebugInfo/CodeView/Formatters.cpp [for host]', configuration: 64450c7aedb07eab037a2a7160d32cfc5d48c8a5dc3d1b39a22517af8ce14772]
(cd /build/locadmin/.cache/bazel/_bazel_root/3c3553b5169933bb2d3ad18fa8d54dcd/execroot/io_kythe && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
    PWD=/proc/self/cwd \
  /usr/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++17' -MD -MF bazel-out/host/bin/external/org_llvm/_objs/LLVMDebugInfoCodeView/Formatters.d '-frandom-seed=bazel-out/host/bin/external/org_llvm/_objs/LLVMDebugInfoCodeView/Formatters.o' -iquote external/org_llvm -iquote bazel-out/host/bin/external/org_llvm -iquote external/net_zlib -iquote bazel-out/host/bin/external/net_zlib -isystem external/org_llvm/include -isystem bazel-out/host/bin/external/org_llvm/include -isystem external/net_zlib/zlib/include -isystem bazel-out/host/bin/external/net_zlib/zlib/include -g0 -g0 '-std=c++17' -Ibazel-out/host/bin/external/org_llvm/lib/DebugInfo/CodeView -Iexternal/org_llvm/lib/DebugInfo/CodeView -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/org_llvm/lib/DebugInfo/CodeView/Formatters.cpp -o bazel-out/host/bin/external/org_llvm/_objs/LLVMDebugInfoCodeView/Formatters.o)
ERROR: /build/locadmin/.cache/bazel/_bazel_root/3c3553b5169933bb2d3ad18fa8d54dcd/external/org_llvm/BUILD.bazel:208:1: C++ compilation of rule '@org_llvm//:LLVMDebugInfoCodeView' failed (Exit 1) clang failed: error executing command /usr/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 36 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/org_llvm/lib/DebugInfo/CodeView/DebugLinesSubsection.cpp:9:
In file included from external/org_llvm/include/llvm/DebugInfo/CodeView/DebugLinesSubsection.h:12:
external/org_llvm/include/llvm/ADT/StringRef.h:22:10: fatal error: 'string_view' file not found
#include <string_view>
         ^~~~~~~~~~~~~
1 error generated.
ERROR: /build/mykythedir/kythe/kythe/cxx/extractor/BUILD:128:1 C++ compilation of rule '@org_llvm//:LLVMDebugInfoCodeView' failed (Exit 1) clang failed: error executing command /usr/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 36 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 5.443s, Critical Path: 3.63s
INFO: 3 processes: 3 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

I couldn’t able to get anything out of this error msg. Can you please check it once.

Thanks,
Aashish

**Comment by shahms** [comment]
can you paste the output of `/usr/bin/clang-8 -x c++ -E -v -` ?

**Comment by aashish29n** [comment]
Hi,

This is the output of /usr/bin/clang-8 -x c++ -E -v -

clang version 8.0.0-3~ubuntu16.04.1 (tags/RELEASE_800/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/lib/llvm-8/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -v -resource-dir /usr/lib/llvm-8/lib/clang/8.0.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/backward -internal-isystem /usr/include/clang/8.0.0/include/ -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-8/lib/clang/8.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /build/mykythedir/kythe -ferror-limit 19 -fmessage-length 78 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o - -x c++ - -faddrsig
clang -cc1 version 8.0.0 based upon LLVM 8.0.0 default target x86_64-pc-linux-gnu
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0"
ignoring duplicate directory "/usr/include/clang/8.0.0/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0
 /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0
 /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/backward
 /usr/include/clang/8.0.0/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.

Thanks,
Aashish Aggarwal

**Comment by shahms** [comment]
`Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0`

I don't know why clang is picking such an old version of libstdc++ to use, but you need at least libstdc++ 7.1 for string_view

https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html

**Comment by shahms** [comment]
You need to use a newer clang.
