### ISSUE TITLE
web/ui folder is not present in Kythe versions.

### ISSUE THREAD

**Issue by aashish29n** [kythe/kythe#4532]
Hi,
I am trying to Enable web UI for kythe but i got stuck in this step.
It is mentioned in Readme file that to Launch Kythe's service APIs as an HTTP server i have to run this command : -
/opt/kythe/tools/http_server --serving_table "$SERVING" \
  --public_resources /opt/kythe/web/ui --listen localhost:9898

But i couldn’t able to find /opt/kythe/web/ui in my Kythe directory.
i am using kythe-v0.0.37.
These are my os Configs: -
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

Need Help!!
Thanks,
Aashish Aggarwal

**Comment by shahms** [comment]
The documentation is incorrect; the web UI is unsupported and no longer shipped with the Kythe release.  The general recommendation is to use something like https://groups.google.com/g/kythe/c/9XzG5e0JyeQ/m/BRLGTfm-CwAJ

**Comment by achew22** [comment]
@shahms I think, maybe, that link is an internal to Google link. On my account I get a 404. Could I trouble you to find the external form of it, or give more details in this thread?

**Comment by achew22** [comment]
Nevermind, given a little bit of URL guessing I was able to come up with https://groups.google.com/forum/#!topic/kythe/9XzG5e0JyeQ

**Comment by shahms** [comment]
It should be an external link to our mailing list (and it works for me externally).  You should be able to get to the mailing list from https://www.kythe.io/community/

**Comment by snnn** [comment]
I couldn't get "underhood" built, but the deprecated builtin UI still works fine for me.

```
$ bazel build -c opt //treetide/... 
ERROR: /data/os/underhood/treetide/underhood/BUILD:12:16: in _haskell_library rule //treetide/underhood:frontend_api: 
Traceback (most recent call last):
	File "/data/os/underhood/treetide/underhood/BUILD", line 12
		_haskell_library(name = 'frontend_api')
	File "/home/chasun/.cache/bazel/_bazel_chasun/4783cea10e0b303e4ce8022e2aa959eb/external/rules_haskell/haskell/private/haskell_impl.bzl", line 389, in haskell_library_impl
		cc_interop_info(ctx)
	File "/home/chasun/.cache/bazel/_bazel_chasun/4783cea10e0b303e4ce8022e2aa959eb/external/rules_haskell/haskell/cc.bzl", line 112, in cc_interop_info
		cc_toolchain.ar_executable()
'string' object is not callable
``

Command to build the old UI:
```
export LEIN_JAVA_CMD=/usr/java/jdk1.8.0_251/bin/java
bazel --server_javabase=/usr/java/jdk1.8.0_251  build   //kythe/web/ui:all
sudo mkdir -p /opt/kythe/web/ui/
sudo cp -r kythe/web/ui/resources/public/* /opt/kythe/web/ui/
```
Then copy the 'bazel-bin/kythe/web/ui/resources/public/js' folder to /opt/kythe/web/ui/

**Comment by ivucica** [comment]
I've done this

```
rm -rf /tmp/kythe-resp
cp -Rav bazel-bin/kythe/web/ui/resources/public /tmp/kythe-resp
cp -Rav kythe/web/ui/resources/public/* /tmp/kythe-resp
${KYTHE_DIR}/tools/http_server --public_resources /tmp/kythe-resp --listen localhost:8080 --serving_table .kythe_serving
```

(`$KYTHE_DIR` being the equivalent of `/opt/kythe`.)
