### ISSUE TITLE
compdb runextractor should allow continuing on error

### ISSUE THREAD

**Issue by shahms** [kythe/kythe#4534]
Currently cmake/compdb extraction will exit if any of the subcommands fails.  We should allow continuing to extract to allow partial builds to extract as much as possible, rather than merely all-or-nothing.  It appears as though the use of `errgroup` here: https://github.com/kythe/kythe/blob/41af1b272687fe7183419e53f9c6e1ed1b8d9a0c/kythe/go/extractors/config/runextractor/compdb/compdb.go#L56 is at fault

**Comment by pirama-arumuga-nainar** [comment]
Would it be also possible to report the source files that failed extraction?  It'd help to keep track of paths with known failure and alert on new failures.  No worries if this is infeasible - the failure counter is a good approximation.

**Comment by shahms** [comment]
@justbuchanan 's change should log the underlying errors when a compilation fails, but it isn't really feasible to dig into those and find the specific source files which failed, IMO

**Comment by pirama-arumuga-nainar** [comment]
No worries.  Thanks for the fix @justbuchanan.

**Comment by justbuchanan** [comment]
Sure thing, @pirama-arumuga-nainar. I added a bit more detail to the error message in https://github.com/kythe/kythe/pull/4546, which includes the source file.
