### ISSUE TITLE
Kythe with coc.nvim

### ISSUE THREAD

**Issue by jasontcole** [kythe/kythe#4568]
I use Kythe with coc.nvim, because coc.nvim (or my LSP?) has issues with goto definitions for proto files that Kythe does not.  The problem is now Kythe interferes with autocompletion particularly when I select an autocomplete option in the pum.  I didn't see a reference to Kythe settings.  Can anyone provide a suggestion? 

![image](https://user-images.githubusercontent.com/62342797/85906254-b922ae00-b7db-11ea-94bf-3008ef2d7ba7.png)

```
Error detected while processing function <lambda>119[1]..<SNR>248_show_documentation:
line   32:
E5555: API call: 'width' key must be a positive Integer
```

**Comment by shahms** [comment]
Not without more information, no.  I don't believe any of us use nvim, let alone that particular plugin.
