### ISSUE TITLE
Can't use JDK11 to build web UI

### ISSUE THREAD

**Issue by d** [kythe/kythe#4672]
## Steps to reproduce
* `bazel build --client_env=CC=clang-10 //kythe/web/ui`
* Expected behavior: the clojure script builds with JDK 11
* Actual behavior: errors with output:

```
INFO: Repository org_leiningen instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule lein_repository defined at:
  /home/pivotal/src/google/kythe/third_party/leiningen/lein_repo.bzl:78:34: in <toplevel>
ERROR: An error occurred during the fetch of repository 'org_leiningen':
   Traceback (most recent call last):
	File "/home/pivotal/src/google/kythe/third_party/leiningen/lein_repo.bzl", line 2
		_check_jdk(repository_ctx)
	File "/home/pivotal/src/google/kythe/third_party/leiningen/lein_repo.bzl", line 104, in _check_jdk
		fail(<1 more arguments>)
Leiningen requires JDK8, found: 2020-07-14 (with LEIN_JAVA_CMD=/usr/bin/java)
ERROR: /home/pivotal/src/google/kythe/kythe/web/ui/BUILD:15:8: //kythe/web/ui:prod-js depends on @org_leiningen//:leinbuild in repository @org_leiningen which failed to fetch. no such package '@org_leiningen//': Traceback (most recent call last):
	File "/home/pivotal/src/google/kythe/third_party/leiningen/lein_repo.bzl", line 2
		_check_jdk(repository_ctx)
	File "/home/pivotal/src/google/kythe/third_party/leiningen/lein_repo.bzl", line 104, in _check_jdk
		fail(<1 more arguments>)
Leiningen requires JDK8, found: 2020-07-14 (with LEIN_JAVA_CMD=/usr/bin/java)
ERROR: Analysis of target '//kythe/web/ui:ui' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.237s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

```

## My environment
* OS: Ubuntu 20.04
* `/usr/bin/java -version` output:
   ```
   openjdk version "11.0.8" 2020-07-14
   ```

### Workaround
* `apt install openjdk-8-jdk`
* `bazel build --client_env=CC=clang-10 --client_env=LEIN_JAVA_CMD=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java //kythe/web/ui`

Is this because of #3638 ?

**Comment by shahms** [comment]
It's because Leiningen requires JDK8 which that PR enforces via a readable error message instead of much less explicit failures when attempting to actually build the UI.

That aside, the UI itself remains in the repository as a concession to those who may still be using it but it is no longer supported.

**Comment by shahms** [comment]
(The other UI I'm aware of is https://github.com/TreeTide/underhood, but I haven't heard much from @robinp in a while so I don't know what its current status is)

**Comment by robinp** [comment]
@shahms re underhood: It's there and functional, but not production-ready. I was about to add expandable callchain support, but found that the Go indexer didn't emit caller information, so got a bit sidetracked (sidenote: unless I messed something, it seems like loading a bit differently sorted entries dump into Postgres for further querying is ~100x faster than running the postprocessing pipeline, which for non-gigantic codebases, could be viable. But this is too early to say).

If someone is interested in Underhood, I can provide support how to deploy / improve it. I have some improvements on the https://github.com/TreeTide/underhood/commits/robinp-uispeed branch, but I add stuff pretty irregularly and at low pace.

**Comment by creachadair** [comment]
> I was about to add expandable callchain support, but found that the Go indexer didn't emit caller information

This seems wrong, can you say more about what you mean by caller information? The indexer should be emitting blame edges and call references, which should be sufficient to reconstruct the call graph. Is there some other piece that needs updated?

**Comment by jaysachs** [comment]
Clicking on `Reset` [here](https://cs.opensource.google/go/x/text/+/master:runes/runes.go;l=60;drc=2df9074612f50810d82416d2229398a1e7188c5c) demonstrates that the Go indexer does produce data for call graphs.

Perhaps the issue is in the post-processing / serving query you're using?
