### ISSUE TITLE
Errors during test of `bazel test //kythe/...`

### ISSUE THREAD

**Issue by YifanTian** [kythe/kythe#4902]
After following everything and installing everything in kythe get stared page. Here is the error I get from running `bazel test //kythe/...`

`WARNING: /Users/yifant/Desktop/Migration/kythe/kythe/go/extractors/config/smoke/BUILD:17:8: in go_test rule //kythe/go/extractors/config/smoke:smoke_test: target '//kythe/go/extractors/config/smoke:smoke_test' depends on deprecated target '//kythe/go/platform/kindex:kindex': Please use //kythe/go/platform/kzip
WARNING: /Users/yifant/Desktop/Migration/kythe/kythe/go/platform/analysis/local/BUILD:5:11: in go_library rule //kythe/go/platform/analysis/local:local: target '//kythe/go/platform/analysis/local:local' depends on deprecated target '//kythe/go/platform/kindex:kindex': Please use //kythe/go/platform/kzip
INFO: Analyzed 2359 targets (0 packages loaded, 0 targets configured).
INFO: Found 1551 targets and 808 test targets...
**ERROR:** /Users/yifant/Desktop/Migration/kythe/kythe/cxx/verifier/BUILD:9:8: Executing genrule //kythe/cxx/verifier:parser failed: (Exit 1): bash failed: error executing command /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; /usr/bin/bison -o bazel-out/darwin-fastbuild/bin/kythe/cxx/verifier/parser.yy.cc kythe/cxx/verifier/assertions.yy'

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; /usr/bin/bison -o bazel-out/darwin-fastbuild/bin/kythe/cxx/verifier/parser.yy.cc kythe/cxx/verifier/assertions.yy'

Use --sandbox_debug to see verbose messages from the sandbox
kythe/cxx/verifier/assertions.yy:4.9-25: syntax error, unexpected identifier, expecting string
**ERROR:** /Users/yifant/Desktop/Migration/kythe/kythe/cxx/verifier/BUILD:28:11 Middleman _middlemen/_S_Skythe_Scxx_Sverifier_Clexparse-BazelCppSemantics_build_arch_darwin-fastbuild failed: (Exit 1): bash failed: error executing command /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; /usr/bin/bison -o bazel-out/darwin-fastbuild/bin/kythe/cxx/verifier/parser.yy.cc kythe/cxx/verifier/assertions.yy'

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; /usr/bin/bison -o bazel-out/darwin-fastbuild/bin/kythe/cxx/verifier/parser.yy.cc kythe/cxx/verifier/assertions.yy'

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 7.220s, Critical Path: 4.65s
INFO: 137 processes: 83 internal, 54 darwin-sandbox.
FAILED: Build did NOT complete successfully
//kythe/cxx/common:file_vname_generator_test                    (cached) PASSED in 3.4s
//kythe/cxx/common:json_proto_test                                    NO STATUS
//kythe/cxx/common:kythe_uri_test                                     NO STATUS
//kythe/cxx/common:kzip_reader_test                                   NO STATUS`

**Comment by jaysachs** [comment]
Seems like you're picking up /usr/bin/bison on OS X, which is bison-2.3;
you need 3.0.4. (Possibly the stock version of flex might be engaging as
well, but I don't see that in your log.)

The link to https://kythe.io/getting-started-macos/ is not super-obvious
from https://kythe.io/getting-started/ ... Ihttps://
github.com/kythe/kythe/issues/4903 to make that more discoverable.
Regardless, the instructions there should unblock you. (Technically you
shouldn't need bazelisk but it won't hurt.)

**Comment by YifanTian** [comment]
Hi @jaysachs I think your suggestion is useful. The previous error is gone. But there is a new error I get from running `bazel test //kythe/...`

external/com_google_protobuf/src/google/protobuf/port_def.inc:175:44: note: expanded from macro 'PROTOBUF_DEPRECATED'
#define PROTOBUF_DEPRECATED __attribute__((deprecated))
                                           ^
1 warning generated.
INFO: From Compiling kythe/cxx/doc/doc.cc:
In file included from kythe/cxx/doc/doc.cc:38:
In file included from ./kythe/cxx/doc/html_markup_handler.h:20:
./kythe/cxx/doc/markup_handler.h:99:45: warning: 'kind' is deprecated [-Wdeprecated-declarations]
  int link_priority() const { return -link_.kind(); }
                                            ^
bazel-out/darwin-fastbuild/bin/kythe/proto/common.pb.h:1623:3: note: 'kind' has been explicitly marked deprecated here
  PROTOBUF_DEPRECATED ::kythe::proto::common::Link_Kind kind() const;
  ^
external/com_google_protobuf/src/google/protobuf/port_def.inc:175:44: note: expanded from macro 'PROTOBUF_DEPRECATED'
#define PROTOBUF_DEPRECATED __attribute__((deprecated))
                                           ^
1 warning generated.
**ERROR:** /private/var/tmp/_bazel_yifant/a629647d4b9faebf348d6c9c4b753f7e/external/org_sourceware_libffi/BUILD.bazel:22:15: CcConfigureMakeRule external/org_sourceware_libffi/libffi/include failed: (Exit 2): bash failed: error executing command /bin/bash -c bazel-out/darwin-fastbuild/bin/external/org_sourceware_libffi/libffi_foreign_cc/wrapper_build_script.sh

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c bazel-out/darwin-fastbuild/bin/external/org_sourceware_libffi/libffi_foreign_cc/wrapper_build_script.sh

Use --sandbox_debug to see verbose messages from the sandbox
rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
rules_foreign_cc: Printing build logs:
_____ BEGIN BUILD LOGS _____

Bazel external C/C++ Rules. Building library libffi

Environment:______________
DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
TMPDIR=/var/folders/0v/yqttf0ns0qz7tw6jvpjfxf5000jrvs/T/
SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk
BUILD_WRAPPER_SCRIPT=bazel-out/darwin-fastbuild/bin/external/org_sourceware_libffi/libffi_foreign_cc/wrapper_build_script.sh
EXT_BUILD_ROOT=/private/var/tmp/_bazel_yifant/a629647d4b9faebf348d6c9c4b753f7e/sandbox/darwin-sandbox/1160/execroot/io_kythe
XCODE_VERSION_OVERRIDE=12.3.0.12C33

**Comment by jaysachs** [comment]
Ah, that was an issue introduced in pr/4890
<https://github.com/kythe/kythe/pull/4890> and fixed in pr/4905
<https://github.com/kythe/kythe/pull/4905>. (We don't have presubmits
covering OS X.)
