### ISSUE TITLE
Support option in verifier to ignore goals from certain files

### ISSUE THREAD

**Issue by nbeloglazov** [kythe/kythe#5029]
With wide-spread support of aspect-based bazel extractors it's now possible to write Kythe tests that extract kzips files from real targets. These tests work in the following way:

1. Extract kzips from targets.
2. Pass kzips to a test runner that invokes individual indexers on kzips.
3. Pass indexed data to the verifier that reads goals from file nodes.

This approach allows for proper testing of cross-language integration: lang A transpiled to lang B as part of bazel building. Kzips of both lang A and lang B are passed to indexers and then verifier ensures that `generates` or `imputes` edges are present. One problem with that approach that during transpilation of a file in lang A to lang B, the transpiler retains comments from the original file. These comments can be `//- ...` comments indented for verifier. So we end up with 2 files having same `//- ...` comments: original `foo.langa` and the generated `foo.langb`. 

Possible workaround is to unpack kzips, extract only the files that need to be verified and pass them explicitly to the verifier together with the indexed data. But that requires an extra step in the test process and feels unnecessary.

**Comment by shahms** [comment]
Or specify the files containing goals as part of the test target definition.  It's a bit redundant, but explicit.

**Comment by nbeloglazov** [comment]
Yes, that's also possible. Though from "ownership" perspective it's a bit that same file is used by multiple targets. The ideal test setup in my mind is something like:

```
js_library(
  name = "foo",
  srcs = ["foo.js"],
)

ts_library(
  name = "bar",
  srcs = ["bar.ts"],
  deps = [":foo"],
)

kythe_indexing_test(
  name = "js_ts_integration",
  targets = [":foo", ":bar"],
)
```

Now what you are proposing is the following:

```
kythe_indexing_test(
  name = "js_ts_integration",
  targets = [":foo", ":bar"],
  files_to_verify = ["foo.js", "bar.ts"],
)
```
?

**Comment by shahms** [comment]
Right, conceptually it's:

```
kythe_verifier_test(
  name = "...",
  srcs = [<files with verifier goals>],
  deps = [<targets which produce graph data>]
)
```
being able to omit the `srcs` attribute to pull the goals from file nodes is a simplification for when the goals are wholly contained by the file nodes to more easily accommodate "trivial" self-contained tests (which are far and away the most common), but that doesn't really hold here.

**Comment by nbeloglazov** [comment]
What is `kythe_verifier_test`? I don't see it anywhere in github repo or google3. That seems to be what I'm incrementally working towards with JS indexing tests. Want to make sure I'm implementing something that then turns out not needed as it's implemented by you or someone else from the kythe team.

**Comment by shahms** [comment]
https://github.com/kythe/kythe/blob/7babd407db6e5e6918634df063cd972f4240fc54/tools/build_rules/verifier_test/verifier_test.bzl#L313

**Comment by nbeloglazov** [comment]
Went with the approach of explicitly passing files to verify.
