### ISSUE TITLE
how can i find the web ui in release package?

### ISSUE THREAD

**Issue by IANTHEREAL** [kythe/kythe#5138]
I can't find the web/ui resource in the recent release package, but `README.md` tell that the it should have. And I try the `kythe/web/ui`, but it can't work

**Comment by creachadair** [comment]
It looks like we need to update the README. Per [Kythe Examples](https://kythe.io/examples/#visualizing-cross-references):

> Note: Version v0.0.30 is the latest version that includes the web UI. If you want a newer Kythe than this, you’ll need to build from source.
