### ISSUE TITLE
kythe CI is broken with Bazel@Head

### ISSUE THREAD

**Issue by mai93** [kythe/kythe#5287]
`managed_directories` was deprecated in [this commit](https://github.com/bazelbuild/bazel/commit/ab24880012a3e661d4baeba39517d8a48fcf653c) and this is causing kythe CI to fail when tested with Bazel@Head ([error](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2480#593d7331-7561-4742-99d8-a823021e9797)). You can follow the instructions in https://github.com/bazelbuild/bazel/issues/15463 for more information on how to migrate away from using `managed_directories`.

**Comment by shahms** [comment]
Cody, I think you have the most state on this?

**Comment by shahms** [comment]
fixed
