### ISSUE TITLE
Required bazel version oddly specific

### ISSUE THREAD

**Issue by hzeller** [kythe/kythe#5366]
The repo only works with Bazel _exactly_ 5.0.0 as required in the [.bazelversion](https://github.com/kythe/kythe/blob/21d416c73e94cc07704170f8fff37a25275fe99b/.bazelversion) file and in the min/max version range of version.bzl

https://github.com/kythe/kythe/blob/21d416c73e94cc07704170f8fff37a25275fe99b/version.bzl#L1-L5

This essentially makes it impossible to use on a system with some pre-installed bazel version and would require to download an somewhat old version.
It would be good if `.bazelversion` does not exist (from what I can tell it exactly ties to a particular bazel version) and if `MIN_VERSION` and`MAX_VERSION` are relaxed to the extend possible and compatible (current 5.x bazel version is [5.3.0](https://github.com/bazelbuild/bazel/releases/tag/5.3.0).

**Comment by shahms** [comment]
We only verify the Kythe builds and runs with particular Bazel versions.  Any other versions are unsupported. These files are also used by our CI system to know which versions of Bazel should be tested.

**Comment by shahms** [comment]
See https://github.com/kythe/kythe/pull/5367 updating this, however.

**Comment by shahms** [comment]
Note: we recommend using [bazelisk](https://github.com/bazelbuild/bazelisk), which will read the `.bazelversion` file in a repository and grab an appropriate version of Bazel for that project.
