### ISSUE TITLE
Flag --incompatible_config_setting_private_default_visibility will break Kythe in a future Bazel release

### ISSUE THREAD

**Issue by keertk** [kythe/kythe#5453]
Incompatible flag `--incompatible_config_setting_private_default_visibility` will be enabled by default in a future Bazel release [1], thus breaking Kythe.

The flag is documented here: https://github.com/bazelbuild/bazel/issues/12933.

Please check the following CI builds for build and test results:

- [Ubuntu 20.04 LTS (OpenJDK 11, gcc 9.4.0)](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a207-ed79-470d-aadc-b579189ab285)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

[1] The target release hasn't been determined yet. Our tool will update the issue title once the flag flip has been scheduled.

**Comment by shahms** [comment]
It looks like this is a problem with the Go rules:
```
(01:15:45) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/226b49198bc606791e41a1a39aa77815/external/io_bazel_rules_go/BUILD.bazel:106:10: in go_config rule @io_bazel_rules_go//:go_config: target '@io_bazel_rules_go//go/private:stamp' is not visible from target '@io_bazel_rules_go//:go_config'. Check the visibility declaration of the former target if you think the dependency is legitimate
```

**Comment by shahms** [comment]
I can't reproduce this with just the flag, does it require a version of Bazel newer than 5.3.2?

**Comment by shahms** [comment]
Ah, nevermind, needed --incompatible_enforce_config_setting_visibility as well.
