### ISSUE TITLE
Flag --incompatible_disable_starlark_host_transitions will break Kythe in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [kythe/kythe#5487]
Incompatible flag `--incompatible_disable_starlark_host_transitions` will be enabled by default in the next major release (Bazel 7.0), thus breaking Kythe. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: [bazelbuild/bazel#17032](https://github.com/bazelbuild/bazel/issues/17032).

Please check the following CI builds for build and test results:

- [Ubuntu 20.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1390#0185940e-47e5-42f6-8763-cd5f3f3fa30e)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by shahms** [comment]
Great. This (or at least the first) failure is due to `bazel_build_rules_nodejs` which is *already* problematic to update

**Comment by shahms** [comment]
It looks like the only remaining breakage is rules_jvm_external for which we'll need a new release as the most recent (4.5) still uses `host = "cfg"`

**Comment by shs96c** [comment]
There are no more `host = "cfg"` references in the `HEAD` of `master` of `rules_jvm_external`, and I'm [currently bumping the version of rules_nodejs](https://github.com/bazelbuild/rules_jvm_external/pull/861) Hopefully those will resolve the issues you're seeing. How do we test to ensure this is fixed?

**Comment by sgowroji** [comment]
Hi Team, Any update on this issue?

**Comment by shahms** [comment]
The latest version of bazel (6.2) ships with a bazel_tools repository which depends on a version of rules_license repository which is incompatible with that flag, which complicates testing.

**Comment by shahms** [comment]
```
$ bazel test --incompatible_disable_starlark_host_transitions //kythe/...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 2bcb2976-afe2-4b71-ace0-cb2aeff8db0e
WARNING: --remote_upload_local_results is set, but the remote cache does not support uploading action results or the current account is not authorized to write local results to the remote cache.
ERROR: Traceback (most recent call last):
        File "/usr/local/google/home/shahms/.cache/bazel/_bazel_shahms/kythe_shared/external/rules_license/rules/license.bzl", line 51, column 41, in <toplevel>
                "license_kinds": attr.label_list(
Error in label_list: 'cfg = "host"' is deprecated and should no longer be used. Please use 'cfg = "exec"' instead.
...
Repository rule http_archive defined at:
  /usr/local/google/home/shahms/.cache/bazel/_bazel_shahms/kythe_shared/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: /usr/local/google/home/shahms/.cache/bazel/_bazel_shahms/kythe_shared/external/bazel_tools/third_party/ijar/BUILD:47:11: error loading package '@bazel_tools//third_party/zlib': initialization of module 'rules/license.bzl' failed and referenced by '@bazel_tools//third_party/ijar:zlib_client'
```

**Comment by shahms** [comment]
(This essentially leaves that flag unusable in any repository that uses http_archive, which is probably most of them).
