### ISSUE TITLE
migrate TS rules from rules_nodejs to rules_ts

### ISSUE THREAD

**Issue by jaysachs** [kythe/kythe#5490]
Specifically, migrate from https://bazelbuild.github.io/rules_nodejs/ to https://github.com/aspect-build/rules_ts

This will unblock moving to modern versions of the tscompiler dependency.

**Comment by jaysachs** [comment]
Plan of action:
1. Introduce a `codejson` (or similar) fact for MarkedSource use.
2. Update proxystub to convert `codejson` to `code` and the payload to binary encoded proto
3. Update the TS indexer to emit this `codejson` fact instead of `code` and remove its dependency on proto
4. Update the TS build rules to `rules_ts`

**Comment by shahms** [comment]
The rules still need to be migrated :-)

**Comment by jaysachs** [comment]
Why the assumption of one PR to fix an issue?

**Comment by creachadair** [comment]
> > Why the assumption of one PR to fix an issue?
> 
> I think it looks for some magic words in the description/title, but can't recall the details.
> 

If you write "Updates #xx" it will tag the issue without closing it; the words "Fix" and "Fixes" (and maybe some others) cause it to close the issue when the PR merges. 

For better or worse.
