### ISSUE TITLE
Fix and re-enable fuchsia_extractor tests

### ISSUE THREAD

**Issue by shahms** [kythe/kythe#5548]
Updating the C++ protobuf dependency broke the fuchsia extractor tests due to linker errors. These errors appear to be because protobuf restructured how their targets were laid out and however Rust is linking these targets is entirely too picky about multiple identical definitions.

I've disabled the targets:
```
//kythe/rust/fuchsia_extractor:fuchsia_extractor_lib_test       FAILED TO BUILD
//kythe/rust/fuchsia_extractor:fuchsia_extractor_test           FAILED TO BUILD
```

to unblock this.

**Comment by wcalandro** [comment]
Closing because the fuchsia extractor is no longer present
