### ISSUE TITLE
Segmentation fault when indexing chromium compilation 

### ISSUE THREAD

**Issue by jsu6** [kythe/kythe#5707]
Hello,
I finished building the chromium compilation and got chromium_linux.kzip (Here is the [link](https://drive.google.com/file/d/1e0-Zre1xAzYHZCr-_KY4h2Tf5DeDyqpz/view?usp=sharing)) around 4GBs. I want to get its graph representation and I used cxx indexer to index it as `/opt/kythe/indexers/cxx_indexer chromium_linux.kzip > chromium_linux.entries`. However, I got a Segmentation fault when the entries file is around 125GBs like 
```
warning: could not detect path style for 
warning: working directory  is not absolute
*** SIGSEGV received at time=1686842396 on cpu 8 ***
PC: @     0x55999e976bb1  (unknown)  kythe::IndexVFS::FileRecordForPath()
    @     0x5599a3356f3c         64  absl::WriteFailureInfo()
    @     0x5599a3356bd8        288  absl::AbslFailureSignalHandler()
    @     0x7fa21b242520  970895328  (unknown)
    @     0x55999e9780ad       1232  kythe::IndexVFS::FileRecordForPathRoot()
    @     0x55999e977061       1904  kythe::IndexVFS::FileRecordForPath()
    @     0x55999e9780ad       1232  kythe::IndexVFS::FileRecordForPathRoot()
    @     0x55999e977061       1904  kythe::IndexVFS::FileRecordForPath()
    @     0x55999e9780ad       1232  kythe::IndexVFS::FileRecordForPathRoot()
    @     0x55999e977061       1904  kythe::IndexVFS::FileRecordForPath()
    @     0x55999e9780ad       1232  kythe::IndexVFS::FileRecordForPathRoot()
    @     0x55999e977061       1904  kythe::IndexVFS::FileRecordForPath()
    @     0x55999e9780ad       1232  kythe::IndexVFS::FileRecordForPathRoot()
    @     0x55999e977061       1904  kythe::IndexVFS::FileRecordForPath()
    @     0x55999e9780ad       1232  kythe::IndexVFS::FileRecordForPathRoot()
    @     0x55999e977061       1904  kythe::IndexVFS::FileRecordForPath()
    @     0x55999e9780ad       1232  kythe::IndexVFS::FileRecordForPathRoot()
    @     0x55999e977061       1904  kythe::IndexVFS::FileRecordForPath()
    @     0x55999e9780ad       1232  kythe::IndexVFS::FileRecordForPathRoot()
    @     0x55999e977061       1904  kythe::IndexVFS::FileRecordForPath()
    @     0x55999e9780ad       1232  kythe::IndexVFS::FileRecordForPathRoot()
    @     0x55999e977061       1904  kythe::IndexVFS::FileRecordForPath()
    @     0x55999e9780ad       1232  kythe::IndexVFS::FileRecordForPathRoot()
    @     0x55999e977061       1904  kythe::IndexVFS::FileRecordForPath()
    @     0x55999e9780ad       1232  kythe::IndexVFS::FileRecordForPathRoot()
    @     0x55999e977061       1904  kythe::IndexVFS::FileRecordForPath()
    @     0x55999e9780ad       1232  kythe::IndexVFS::FileRecordForPathRoot()
    @     0x55999e977061       1904  kythe::IndexVFS::FileRecordForPath()
    @     0x55999e9780ad       1232  kythe::IndexVFS::FileRecordForPathRoot()
    @     0x55999e977061       1904  kythe::IndexVFS::FileRecordForPath()
    @     0x55999e9780ad       1232  kythe::IndexVFS::FileRecordForPathRoot()
    @     0x55999e977061       1904  kythe::IndexVFS::FileRecordForPath()
    @     0x55999e9780ad       1232  kythe::IndexVFS::FileRecordForPathRoot()
    @ ... and at least 1000 more frames
Segmentation fault (core dumped)
```
Am I building the kzip file incorrectly or using the indexer incorrectly? Any help is appreciated.  

OS: Ubuntu 22.04.2 LTS
CPU: AMD x86_64
RAM: 128GBs
kythe release version: 0.0.61 (passed all bazel tests)

**Comment by shahms** [comment]
I would expect running the C++ indexer as a single binary over a 4GB kzip to take until the heat death of the universe to complete. I'm a little surprised by the stack-overflow segmentation fault, but given the `warning: working directory  is not absolute` the comment https://github.com/kythe/kythe/blob/7880a91002f0fb41f161b43ad7e0e4be76d0dbe9/kythe/cxx/indexer/cxx/KytheVFS.cc#L186 is clearly incorrect.

**Comment by jsu6** [comment]
I ran a similar command to the same kzip file with updated kythe and still got a Segmentation fault when the entries file is around 18GBs.
Command: `/opt/kythe/indexers/cxx_indexer -ignore_unimplemented=true --experimental_dynamic_claim_cache="--SERVER=localhost:11211" --cache="--SERVER=localhost:11211" ~/chromium_linux.kzip > ~/chromium_linux.entries`  
Error message: 
```
warning: could not detect path style for 
*** SIGSEGV received at time=1687211022 on cpu 11 ***
PC: @     0x7feb24dc7116  (unknown)  std::__cxx11::basic_string<>::basic_string()
    @     0x5623a5f7b03c         64  absl::WriteFailureInfo()
    @     0x5623a5f7acd8        288  absl::AbslFailureSignalHandler()
    @     0x7feb24a75520  (unknown)  (unknown)
    @ ... and at least 1 more frames
Segmentation fault (core dumped)
```

**Comment by jsu6** [comment]
I didn't see a verbose flag for the binary. Is there any way I can do to provide more debug information?

**Comment by shahms** [comment]
You can see if setting `GOOGLE_LOGTOSTDERR=1` includes relevant information.

**Comment by jsu6** [comment]
I got this error message in the beginning by running `/opt/kythe/indexers/cxx_indexer -ignore_unimplemented=true GOOGLE_LOGTOSTDERR=1 --experimental_dynamic_claim_cache="--SERVER=localhost:11211" --cache="--SERVER=localhost:11211" ~/chromium_linux.kzip > ~/chromium_linux.entries`:
```
F20230620 15:33:17.349947 736638 frontend.cc:214] Check failed: llvm::StringRef(file_or_cu).endswith(".kzip") 
*** Check failure stack trace: ***
    @     0x560515e1bd5d  google::LogMessage::Fail()
    @     0x560515e1b1b8  google::LogMessage::SendToLog()
    @     0x560515e1ba3d  google::LogMessage::Flush()
    @     0x560515e1f589  google::LogMessageFatal::~LogMessageFatal()
    @     0x5605111df4c5  kythe::IndexerContext::LoadDataFromKZip()
    @     0x5605111e1b01  kythe::IndexerContext::EnumerateCompilations()
    @     0x5605111cf7d1  kythe::main()
    @     0x5605111cfa72  main
    @     0x7f8a85df8d90  (unknown)
    @     0x7f8a85df8e40  __libc_start_main
    @     0x5605111cefe5  _start
    @              (nil)  (unknown)
*** SIGABRT received at time=1687289597 on cpu 1 ***
PC: @     0x7f8a85e65a7c  (unknown)  pthread_kill
    @     0x560515d4d03c         64  absl::WriteFailureInfo()
    @     0x560515d4ccd8        288  absl::AbslFailureSignalHandler()
    @     0x7f8a85e11520  (unknown)  (unknown)
Aborted (core dumped)
```

**Comment by shahms** [comment]
`GOOGLE_LOGTOSTDERR=1` needs to be set as an environment variable

**Comment by jsu6** [comment]
It seems the patch doesn't work. Here is the error message:
```
warning: could not detect path style for
W20230623 20:09:27.999822 947303 KytheVFS.cc:68] working directory  is not absolute
*** SIGSEGV received at time=1687565368 on cpu 7 ***
PC: @     0x7f311c3bb116  (unknown)  std::__cxx11::basic_string<>::basic_string()
    @     0x55573af2cc7c         64  absl::WriteFailureInfo()
    @     0x55573af2c918        288  absl::AbslFailureSignalHandler()
    @     0x7f311c069520  (unknown)  (unknown)
    @ ... and at least 1 more frames
```

Meanwhile, I am trying to build kzip files for parallelization by using extractor `/opt/kythe/tools/runextractor compdb -extractor /opt/kythe/extractors/cxx_extractor -path out/Debug/compile_commands.json`. However, when I used `time cat units | parallel --gnu -L1 /opt/kythe/indexers/cxx_indexer --ignore_unimplemented=true --experimental_dynamic_claim_cache="--SERVER=localhost:11211" -cache="--SERVER=localhost:11211" | /opt/kythe/tools/dedup_stream | /opt/kythe/tools/write_entries -workers 32 -graphstore ~/chromium_graph` to create a graph based on extracted kzip files (62618 files with ~155GBs), lots of No such file or directory errors happened:

```
Error: Errors during indexing:error reading '../../third_party/blink/renderer/modules/csspaint/paint_worklet_global_scope.cc': No such file or directory
       0         0 claims approved/rejected (0.000000 reject fraction)
1 error generated.
Error: Errors during indexing:error reading '../../content/renderer/render_frame_impl_browsertest.cc': No such file or directory
       0         0 claims approved/rejected (0.000000 reject fraction)
1 error generated.
Error: Errors during indexing:error reading '../../third_party/blink/renderer/core/html/anchor_element_metrics_sender_test.cc': No such file or directory
       0         0 claims approved/rejected (0.000000 reject fraction)
1 error generated.
Error: Errors during indexing:error reading '../../third_party/blink/renderer/core/fragment_directive/same_block_word_iterator_test.cc': No such file or directory
       0         0 claims approved/rejected (0.000000 reject fraction)
2023/06/24 00:05:46 dedup_stream: skipped 6719268 records
2023/06/24 00:05:46 Wrote 28510537 entries
``` 
Most errors relate to this relative path format. The problem is probably with ../../ since these files exist when I am in chromium/src/out/Debug. But no matter I call indexer in chromium/src/or chromium/src/out/Debug, the same error messages appear. Or is it because I didn't build the tests since lots of them are test-related files? I generate compile_commands.json by calling `ninja -C out/Debug chromium -t compdb cc cxx objc objcxx > out/Debug/compile_commands.json` and my args.gn is 
```
blink_enable_generated_code_formatting = true
clang_use_chrome_plugins = false
enable_kythe_annotations = true
is_clang = true
is_component_build = true
is_debug = true
symbol_level = 1
``` 
Do I need to worry about these error messages? 

Also, I build chromium_linux.kzip with `/home/yd6/infra/go/src/infra/cmd/package_index/package_index --checkout_dir ./ --path_to_compdb out/Debug/compile_commands.json --path_to_gn_targets out/Debug/gn_targets.json --path_to_archive_output out/Debug/chromium_build.kzip --corpus chromium.googlesource.com/codesearch/builder/src --project chromium --out_dir out/Debug --build_config linux`, but I don't see gn_targets.json is involved by directly using cxx_extractor. Doesn't cxx_extractor need this information?

**Comment by shahms** [comment]
When indexing from a kzip file, the indexer should not be reading from the local filesystem.  In general, relative paths should be fine (with some caveats) but it's hard to say without knowing more.  I don't know what `package_index` is or what `gn_targets.json` contains, so I don't know why `cxx_extractor` might or might not need that information.

**Comment by jsu6** [comment]
Here is link to [package_index](https://source.chromium.org/chromium/infra/infra/+/main:go/src/infra/cmd/package_index/README.md). It says gn_targets.json is for finding all the Mojom targets. I followed it to generate my [gn_targets.json](https://drive.google.com/file/d/1ttI15lAXRFFKJkCsNhur-H4vkkVnDUzG/view?usp=sharing).

**Comment by shahms** [comment]
You'll have to take up issues with that program with the authors; I don't know anything about it or how it may use gn_targets.json (nor even what that is supposed to be).

Note: the various indexers only support being run over kzip files which contain compilations for *that* language.  If, as I suspect, you're running them directly on a kzip which contains multiple languages you are almost certain to see failures of some kind.  There isn't enough information in the stacktrace to say anything relevant, other than that it *looks* like it's attempting to construct a too-large `std::string` instance. This can happen for a variety of reasons, but without more stack information it's not feasible to say.

**Comment by jsu6** [comment]
I see. Thanks for your response!

**Comment by jsu6** [comment]
Hello,
when I was running `~/kythe-v0.0.63/tools/write_tables --entries centries --out serving/ --experimental_beam_pipeline --experimental_beam_columnar_data  -num_workers 20`, I got an error message: `2023/09/28 11:13:26 Pipeline error: panic: failed to encode val KV<0,KV<corpus:"chromium_linux_kythe" path:"build/linux/debian_bullseye_amd64-sysroot/usr/include/X11/extensions/Xge.h",raw_text:"\n Copyright \xa9 2007-2008 Peter Hutterer\n\n Permission is hereby granted, free of charge, to any person obtaining a\n copy of this software and associated documentation files (the \"Software\"),\n to deal in the Software without restriction, including without limitation\n the rights to use, copy, modify, merge, publish, distribute, sublicense,\n and/or sell copies of the Software, and to permit persons to whom the\n Software is furnished to do so, subject to the following conditions:\n\n The above copyright notice and this permission notice (including the next\n paragraph) shall be included in all copies or substantial portions of the\n Software.\n\n THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL\n THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING\n FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER\n DEALINGS IN THE SOFTWARE.\n\n Authors: Peter Hutterer, University of South Australia, NICTA\n\n "> [@0:[[*]]]> [@0:[[*]]] for CoGBK: string field contains invalid UTF-8`
Is there a flag to ignore these kind of error with source code comment? Or is there an efficient way to solve it?

**Comment by shahms** [comment]
it sounds like `/usr/include/X11/extensions/Xge.h` isn't UTF-8 encoded (specifically the copyright symbol `\xa9`).  AFAIK, the C++ indexer and the rest of the pipeline expects source files to be encoded as UTF-8 and not much affordance has been made for files which aren't.  

Please open a separate bug for separate issues.

**Comment by jsu6** [comment]
I don't think it's a bug. I just want to check if there is any shortcut that I missed because I saw this invalid UTF-8 character appearing in https://source.chromium.org/chromiumos/chromiumos/codesearch/+/main:gen/arm-generic/chroot/usr/include/X11/extensions/Xge.h. Especially dealing with chromium source code takes too much time. Thanks for responses!
