### ISSUE TITLE
Error : no such package '@io_kythe//kythe/data': The repository '@io_kythe' could not be resolved: Repository '@io_kythe' is not defined

### ISSUE THREAD

**Issue by sgowroji** [kythe/kythe#5893]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3379#_

Platform: Ubuntu

Logs:
```
ERROR: no such package '@io_kythe//kythe/data': The repository '@io_kythe' could not be resolved: Repository '@io_kythe' is not defined
(03:57:19) ERROR: /var/lib/buildkite-agent/builds/bk-docker-r8lq/bazel-downstream-projects/kythe/WORKSPACE:63:19: no such package '@io_kythe//kythe/data': The repository '@io_kythe' could not be resolved: Repository '@io_kythe' is not defined and referenced by '//external:vnames_config'
(03:57:19) ERROR: Analysis of target '//kythe/cxx/indexer/cxx/testdata/proto:proto_semantic_ref_aw_test_proto_kzip' failed; build aborted: Analysis failed
(03:57:19) INFO: Elapsed time: 1.389s, Critical Path: 0.04s
(03:57:19) INFO: 1 process: 1 internal.
(03:57:19) ERROR: Build did NOT complete successfully
(03:57:19) FAILED:

```
Steps:
```
git clone -v https://github.com/kythe/kythe.git
git reset 47d8a9a27d280e7c71150a1b267f46790ead5fb7 --hard
export USE_BAZEL_VERSION=b3a83a3a3dab0b87952b67cfc7ea8516eabeec4b
sudo apt update && sudo apt -y install bison flex uuid-dev asciidoc graphviz source-highlight
bazel build //kythe/...
```

CC Greenteam @mai93

**Comment by shahms** [comment]
This seems like a bug in Bazel; we define `io_kythe` right here: https://github.com/kythe/kythe/blob/ded645e9f7e7140f5d065fb570d8900f0850150c/WORKSPACE#L1

**Comment by mai93** [comment]
@Wyverald can this be related to https://github.com/bazelbuild/bazel/commit/9be1be93ff17dbb4cf0effb4f885911ec99cc30c

**Comment by sgowroji** [comment]
@meteorcloudy

**Comment by meteorcloudy** [comment]
This is probably due to the enabling of Bzlmod by default: https://github.com/bazelbuild/bazel/issues/18958

Please add `--noenable_bzlmod` in your .bazelrc file if the project isn't yet ready to use Bzlmod.

**Comment by meteorcloudy** [comment]
Similar issue for protobuf: https://github.com/protocolbuffers/protobuf/issues/14383, where Bzlmod is already disabled.

I think @mai93 is correct, I can reproduce the failure with Bazel built at https://github.com/bazelbuild/bazel/commit/9be1be93ff17dbb4cf0effb4f885911ec99cc30c but not its parent commit.

@sgowroji Let's move those two issues to the Bazel repo since it's a Bazel bug, and it should be marked as a release blocker for 7.0.0

**Comment by sgowroji** [comment]
Moved here https://github.com/bazelbuild/bazel/issues/19973
