### ISSUE TITLE
cc_index rule doesn't set log level correctly

### ISSUE THREAD

**Issue by nbeloglazov** [kythe/kythe#6074]
cc_index uses `GLOG_logtostderr` enviroment variable to control logging: https://github.com/kythe/kythe/blob/master/tools/build_rules/verifier_test/cc_indexer_test.bzl#L68

If I understand correctly C++ indexer no longer uses glog library. Instead it uses log library from Abseil: https://github.com/kythe/kythe/blob/master/kythe/cxx/indexer/cxx/BUILD#L65 

Abseil is using different command-line arguments: https://github.com/abseil/abseil-cpp/blob/master/absl/log/flags.h

**Comment by nbeloglazov** [comment]
Additionally it seems like there is pretty much no logging at INFO level done by the C++ indexer? I tried adding `--stderrthreshold=0` when running indexer and nothing was logged. To make sure the option is working I added dummy `LOG(INFO)` call to the indexer and saw its output.

**Comment by shahms** [comment]
It also looks like the Abseil logging library doesn't respect any environment variables directly, outside of Google.  You can use `--fromenv` or `--tryfromenv` to specify a list of flags to read from the environment but that kind of defeats the point.

**Comment by shahms** [comment]
I think the `vmodule` lines might've been relevant, but don't provide enough value that I'm just going to simplify things and delete the obsolete references.
